import { createContext, useContext, useState, useEffect } from 'react'

export const LANGUAGES = [
  { code: 'hi', label: 'हिन्दी', sub: 'Hindi' },
  { code: 'en', label: 'English', sub: 'English' },
  { code: 'mr', label: 'मराठी', sub: 'Marathi' },
  { code: 'bn', label: 'বাংলা', sub: 'Bengali' },
  { code: 'te', label: 'తెలుగు', sub: 'Telugu' },
  { code: 'ta', label: 'தமிழ்', sub: 'Tamil' },
  { code: 'gu', label: 'ગુજરાતી', sub: 'Gujarati' },
  { code: 'kn', label: 'ಕನ್ನಡ', sub: 'Kannada' },
]

export const TRANSLATIONS = {
  hi: {
    slogan: 'संज्ञान शील्ड • धोखाधड़ी से पहले संज्ञान',
    nav: {
      home: 'होम',
      verify: 'सत्यापन वर्कस्पेस',
      history: 'ऑडिट इतिहास',
      learn: 'जागरूकता पाठ',
      report: 'धोखाधड़ी रिपोर्ट',
      emergency: 'आपातकालीन 1930',
      verified: 'प्रमाणित नागरिक',
      historyAction: 'सत्यापन इतिहास',
      reportAction: 'दर्ज रिपोर्ट व एफआईआर',
      alertsAction: 'एसएमएस व यूपीआई अलर्ट',
      signOut: 'लॉग आउट / पहचान बदलें',
    },
    hero: {
      badge: 'एआई-संचालित भारत साइबर सुरक्षा कवच',
      title: 'संदेश, लिंक या निवेश सलाह की जांच करें धोखाधड़ी से पहले!',
      subtitle: 'सुरक्षित और सशक्त भारत के लिए एआई-संचालित सत्यापन प्रणाली',
      desc: 'व्हाट्सएप फॉरवर्ड, टेलीग्राम ट्रेडिंग ग्रुप, सेबी पंजीकरण और यूपीआई हैंडल की तुरंत जांच करें। हर नागरिक के लिए निःशुल्क शून्य-ट्रस्ट सुरक्षा।',
      startBtn: 'सत्यापन शुरू करें',
      learnBtn: 'जागरूकता पाठ देखें',
      stat1: '3.2 लाख+ फ्रॉड रोके गए',
      stat2: '₹42 करोड़ की बचत',
      stat3: 'नागरिकों के लिए 100% निःशुल्क',
    },
    actions: {
      card1Title: 'स्क्रीनशॉट अपलोड करें',
      card1Desc: 'व्हाट्सएप चैट, फर्जी रसीद और टेलीग्राम संदेशों की तत्काल ओसीआर जांच।',
      card1Tag: 'त्वरित ओसीआर',
      card1Action: 'दस्तावेज़ स्कैन करें',

      card2Title: 'संदिग्ध लिंक जांचें',
      card2Desc: 'फर्जी निवेश पोर्टल, एपीके डाउनलोड और फ़िशिंग डोमेन की त्वरित जांच।',
      card2Tag: 'डोमेन व एसएसएल',
      card2Action: 'यूआरएल जांचें',

      card3Title: 'एसएमएस / संदेश जांचें',
      card3Desc: 'बिजली बिल, लॉटरी और बैंक अपडेट के फर्जी संदेशों की पहचान करें।',
      card3Tag: 'एनएलपी भाषा विश्लेषण',
      card3Action: 'संदेश चिपकाएं',

      card4Title: 'डीपफेक व वॉइस जांच',
      card4Desc: 'आर्टिफिशियल इंटेलिजेंस द्वारा बनाई गई फर्जी आवाज और ऑडियो की पहचान।',
      card4Tag: 'वॉइस स्पेक्ट्रम',
      card4Action: 'ऑडियो जांचें',
    },
    verifyBar: {
      tag: 'त्वरित बहु-मोडल सत्यापन बार',
      title: 'संदिग्ध अनुरोध की तुरंत जांच करें',
      privacy: 'शून्य सर्वर स्टोरेज • तत्काल क्रिप्टोग्राफ़िक हैश जांच',
      placeholder: 'यूपीआई आईडी, लिंक, फोन नंबर या संदेश यहाँ चिपकाएँ...',
      paste: 'पेस्ट करें',
      verifyBtn: 'सत्यापन जांचें',
      samplePrompt: 'नमूना परीक्षण करें:',
    },
    howItWorks: {
      tag: 'सुरक्षा प्रक्रिया',
      title: 'संज्ञान शील्ड 3 चरणों में कैसे रक्षा करता है',
      subtitle: 'जटिल साइबर वित्तीय धोखाधड़ी को सेकंडों में पहचानने वाली तकनीक',
      step1Title: '1. इनपुट दें',
      step1Desc: 'संदिग्ध यूपीआई आईडी, लिंक, स्क्रीनशॉट या संदेश चिपकाएं।',
      step2Title: '2. एआई सत्यापन',
      step2Desc: 'सेबी, एनपीसीआई और साइबर अपराध रजिस्ट्री से मिलान कर जोखिम का विश्लेषण।',
      step3Title: '3. स्पष्ट सुरक्षा निर्देश',
      step3Desc: 'तुरंत सुरक्षा स्कोर, 1930 फ्रॉड फ्रीज निर्देश व एफआईआर साक्ष्य सारांश प्राप्त करें।',
    },
    threatRadar: {
      tag: 'लाइव थ्रेट टेलीमेट्री',
      title: 'सक्रिय भारत साइबर फ्रॉड अलर्ट',
      subtitle: 'भारतीय साइबर अपराध समन्वय केंद्र (I4C) के सहयोग से रीयल-टाइम अपडेट',
      alert1Title: 'फर्जी एसबीआई रिवॉर्ड एपीके',
      alert1Desc: 'एसएमएस के जरिए एपीके लिंक भेजकर बैंक ओटीपी चुराने का प्रयास।',
      alert2Title: 'टेलीग्राम पार्ट-टाइम जॉब स्कैम',
      alert2Desc: 'यूट्यूब वीडियो लाइक करने के नाम पर दैनिक मुनाफे का झांसा।',
      alert3Title: 'डिजिटल अरेस्ट सीबीआई फ्रॉड',
      alert3Desc: 'पार्सल में नशीले पदार्थ मिलने का डर दिखाकर वीडियो कॉल पर जबरन वसूली।',
    },
    helplineBanner: {
      goldenHour: 'गोल्डन ऑवर प्रोटोकॉल: 2 घंटे के भीतर कार्रवाई',
      title: 'ऑनलाइन धोखाधड़ी में पैसे गंवाए? तुरंत 1930 डायल करें',
      desc: 'राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल (I4C) लाभार्थी बैंक खातों को तत्काल फ्रीज कर सकता है।',
      callBtn: '1930 पर कॉल करें',
      portalBtn: 'आधिकारिक पोर्टल (MHA)',
    }
  },

  en: {
    slogan: 'Sangyan Shield • Verify Before You Pay',
    nav: {
      home: 'Home',
      verify: 'Verify Workspace',
      history: 'Audit History',
      learn: 'Learn (Micro-Lessons)',
      report: 'Report Fraud',
      emergency: 'Emergency 1930',
      verified: 'Verified Citizen',
      historyAction: 'Verification History',
      reportAction: 'Reported Frauds & FIR Drafts',
      alertsAction: 'SMS & UPI Alert Push',
      signOut: 'Sign Out / Switch Identity',
    },
    hero: {
      badge: 'AI-POWERED BHARAT CYBER DEFENSE',
      title: 'Verify Before You Pay — Protect Against Deepfakes & UPI Fraud!',
      subtitle: 'Sovereign AI Verification Infrastructure for a Safer & Smarter India',
      desc: 'Verify WhatsApp forwards, Telegram trading tips, SEBI numbers, and UPI handles before making any transaction. Instant zero-trust telemetry for every citizen.',
      startBtn: 'Start Checking',
      learnBtn: 'Explore Lessons',
      stat1: '3.2 Lakh+ Scams Flagged',
      stat2: '₹42 Cr Protected',
      stat3: '100% Free for Citizens',
    },
    actions: {
      card1Title: 'Upload Screenshot',
      card1Desc: 'Instant OCR scanning of WhatsApp chats, forged receipts, and Telegram tips.',
      card1Tag: 'Instant OCR',
      card1Action: 'Scan Document',

      card2Title: 'Check a Link',
      card2Desc: 'Inspect fake investment portals, malicious APK downloads, and phishing domains.',
      card2Tag: 'Domain & SSL',
      card2Action: 'Verify URL',

      card3Title: 'Analyze Message',
      card3Desc: 'Detect electricity bill, lottery, and banking SMS phishing lures using NLP.',
      card3Tag: 'NLP Analysis',
      card3Action: 'Paste Message',

      card4Title: 'Deepfake & Voice Scan',
      card4Desc: 'Analyze suspected AI-generated synthetic voice notes and audio calls.',
      card4Tag: 'Voice Spectrum',
      card4Action: 'Inspect Audio',
    },
    verifyBar: {
      tag: 'Fast Multi-Modal Verification Bar',
      title: 'Verify Suspicious Request Now',
      privacy: 'Zero Server Storage • Instant Cryptographic Hash Verification',
      placeholder: 'Paste UPI ID, Link, Phone Number, or SMS Message here...',
      paste: 'Paste',
      verifyBtn: 'Verify Integrity',
      samplePrompt: 'Try test samples:',
    },
    howItWorks: {
      tag: 'Defensive Architecture',
      title: 'How Sangyan Shield Protects You in 3 Steps',
      subtitle: 'Sovereign intelligence stopping financial fraud before irreversible UPI execution',
      step1Title: '1. Submit Input',
      step1Desc: 'Paste suspect UPI VPA, dubious web link, screenshot, or audio clip.',
      step2Title: '2. Deep AI Telemetry',
      step2Desc: 'Matched against SEBI registry, NPCI bank records, and 14,000+ known Ponzi schemes.',
      step3Title: '3. Actionable Defense',
      step3Desc: 'Receive immediate risk score, 1930 bank lien instructions, and downloadable FIR dossier.',
    },
    threatRadar: {
      tag: 'Live Threat Telemetry',
      title: 'Active Bharat Cyber Threat Alerts',
      subtitle: 'Real-time threat intelligence synced with Indian Cyber Crime Coordination Centre (I4C)',
      alert1Title: 'Fake SBI Reward APK Scam',
      alert1Desc: 'Sideloaded malicious APK distributed via SMS stealing mobile banking credentials.',
      alert2Title: 'Telegram YouTube Task Scam',
      alert2Desc: 'Fraudulent part-time video rating schemes demanding progressive deposits.',
      alert3Title: 'Digital Arrest CBI Video Fraud',
      alert3Desc: 'Impersonators posing as customs and police demanding extortion payments via video call.',
    },
    helplineBanner: {
      goldenHour: 'GOLDEN HOUR PROTOCOL: Act within 2 hours',
      title: 'Lost Money to Online Fraud? Dial 1930 Immediately',
      desc: 'The National Cyber Crime Reporting Portal (I4C) can initiate an emergency freeze on recipient accounts.',
      callBtn: 'Call 1930 Now',
      portalBtn: 'Official Portal (MHA)',
    }
  },

  mr: {
    slogan: 'संज्ञान शील्ड • पेमेंट करण्यापूर्वी खात्री करा',
    nav: {
      home: 'मुख्यपृष्ठ',
      verify: 'पडताळणी वर्कस्पेस',
      history: 'ऑडिट इतिहास',
      learn: 'जागरूकता धडे',
      report: 'फसवणूक तक्रार',
      emergency: 'आपत्कालीन 1930',
      verified: 'प्रमाणित नागरिक',
      historyAction: 'पडताळणी इतिहास',
      reportAction: 'नोंदवलेली फसवणूक व एफआयआर',
      alertsAction: 'एसएमएस आणि यूपीआय अलर्ट',
      signOut: 'बाहेर पडा',
    },
    hero: {
      badge: 'एआय-संचालित भारत सायबर सुरक्षा कवच',
      title: 'पैसे भरण्यापूर्वी संदेश, लिंक किंवा गुंतवणुकीच्या सल्ल्याची खात्री करा!',
      subtitle: 'सुरक्षित महाराष्ट्रासाठी आणि भारतासाठी प्रगत एआय पडताळणी प्रणाली',
      desc: 'व्हॉट्सअॅप मेसेज, टेलिग्राम ट्रेडिंग ग्रुप आणि यूपीआय आयडी यांची फसवणूक होण्यापूर्वी त्वरित तपासणी करा.',
      startBtn: 'तपासणी सुरू करा',
      learnBtn: 'धडे एक्सप्लोर करा',
      stat1: '3.2 लाख+ स्कॅम रोखले',
      stat2: '₹42 कोटी संरक्षित',
      stat3: 'नागरिकांसाठी 100% मोफत',
    },
    actions: {
      card1Title: 'स्क्रीनशॉट अपलोड करा',
      card1Desc: 'व्हॉट्सअॅप चॅट आणि पावत्यांचे त्वरित ओसीआर स्कॅनिंग.',
      card1Tag: 'झटपट ओसीआर',
      card1Action: 'दस्तऐवज तपासा',

      card2Title: 'वेब लिंक तपासा',
      card2Desc: 'बनावट गुंतवणूक पोर्टल आणि धोकादायक एपीके डाऊनलोड तपासा.',
      card2Tag: 'डोमेन पडताळणी',
      card2Action: 'यूआरएल तपासा',

      card3Title: 'संदेश तपासा',
      card3Desc: 'लाईट बिल, लॉटरी व बँक अपडेट्सचे खोटे एसएमएस ओळखा.',
      card3Tag: 'मेसेज विश्लेषण',
      card3Action: 'संदेश पेस्ट करा',

      card4Title: 'डीपफेक व व्हॉइस स्कॅन',
      card4Desc: 'एआय निर्मित बनावट आवाज आणि ऑडिओ कॉल्सची तपासणी.',
      card4Tag: 'व्हॉइस स्पेक्ट्रम',
      card4Action: 'ऑडिओ तपासा',
    },
    verifyBar: {
      tag: 'त्वरित पडताळणी बार',
      title: 'संशयास्पद व्यवहाराची त्वरित तपासणी करा',
      privacy: 'शून्य सर्व्हर स्टोरेज • त्वरित सुरक्षा तपासणी',
      placeholder: 'यूपीआय आयडी, लिंक किंवा मेसेज येथे पेस्ट करा...',
      paste: 'पेस्ट करा',
      verifyBtn: 'पडताळणी करा',
      samplePrompt: 'नमुने तपासा:',
    },
    howItWorks: {
      tag: 'सुरक्षा पद्धत',
      title: 'संज्ञान शील्ड ३ टप्प्यांत कसे संरक्षण करते',
      subtitle: 'सायबर फसवणूक रोखणारी भारताची स्वतःची एआय सुरक्षा यंत्रणा',
      step1Title: '१. माहिती प्रविष्ट करा',
      step1Desc: 'संशयास्पद यूपीआय किंवा लिंक येथे पेस्ट करा.',
      step2Title: '२. एआय पडताळणी',
      step2Desc: 'सेबी, एनपीसीआय आणि फसवणूक डेटाबेसशी त्वरित पडताळणी.',
      step3Title: '३. सुरक्षा सूचना',
      step3Desc: 'त्वरित सुरक्षा स्कोर आणि 1930 बँक फ्रीज मार्गदर्शन मिळवा.',
    },
    threatRadar: {
      tag: 'थेट सायबर अलर्ट',
      title: 'सक्रिय भारत सायबर अलर्ट',
      subtitle: 'भारतीय सायबर गुन्हे समन्वय केंद्र (I4C) द्वारे रिअल-टाइम अपडेट्स',
      alert1Title: 'बनावट एसबीआय रिवॉर्ड एपीके',
      alert1Desc: 'एसएमएसद्वारे बनावट ॲप पाठवून बँक खात्यातून पैसे चोरण्याचा प्रयत्न.',
      alert2Title: 'टेलिग्राम पार्ट-टाइम जॉब स्कॅम',
      alert2Desc: 'व्हिडिओ लाईक करण्याच्या नावाखाली मोठी रक्कम उकळण्याचा प्रकार.',
      alert3Title: 'डिजिटल अरेस्ट सीबीआय फ्रॉड',
      alert3Desc: 'पार्सलमध्ये ड्रग्ज सापडल्याची भीती दाखवून पैशांची मागणी.',
    },
    helplineBanner: {
      goldenHour: 'गोल्डन अवर: २ तासांच्या आत तक्रार करा',
      title: 'ऑनलाईन फसवणूक झाली असल्यास त्वरित 1930 वर कॉल करा',
      desc: 'राष्ट्रीय सायबर पोर्टल फसवणूक झालेल्या बँक खात्याला त्वरित गोठवू शकते.',
      callBtn: '1930 वर कॉल करा',
      portalBtn: 'अधिकृत पोर्टल (MHA)',
    }
  },

  bn: {
    slogan: 'সংজ্ঞান শিল্ড • টাকা দেওয়ার আগে যাচাই করুন',
    nav: {
      home: 'হোম',
      verify: 'যাচাই ওয়ার্কস্পেস',
      history: 'অডিট ইতিহাস',
      learn: 'সচেতনতা পাঠ',
      report: 'প্রতারণার অভিযোগ',
      emergency: 'জরুরি 1930',
      verified: 'যাচাইকৃত নাগরিক',
      historyAction: 'যাচাই ইতিহাস',
      reportAction: 'অভিযোগ ও এফআইআর',
      alertsAction: 'এসএমএস ও ইউপিআই সতর্কতা',
      signOut: 'লগ আউট',
    },
    hero: {
      badge: 'এআই-চালিত ভারত সাইবার সুরক্ষা কবচ',
      title: 'টাকা পাঠানোর আগে মেসেজ, লিঙ্ক বা বিনিয়োগের পরামর্শ যাচাই করুন!',
      subtitle: 'নিরাপদ ভারতের জন্য কৃত্রিম বুদ্ধিমত্তা চালিত যাচাইকরণ ব্যবস্থা',
      desc: 'হোয়াটসঅ্যাপ মেসেজ, টেলিগ্রাম ট্রেডিং গ্রুপ ও ইউপিআই হ্যান্ডেল যাচাই করুন প্রতারিত হওয়ার আগেই।',
      startBtn: 'যাচাই শুরু করুন',
      learnBtn: 'পাঠ দেখুন',
      stat1: '৩.২ লাখ+ জালিয়াতি রোধ',
      stat2: '₹৪২ কোটি সংরক্ষিত',
      stat3: 'নাগরিকদের জন্য সম্পূর্ণ বিনামূল্যে',
    },
    actions: {
      card1Title: 'স্ক্রিনশট আপলোড',
      card1Desc: 'হোয়াটসঅ্যাপ চ্যাট ও জাল রসিদের দ্রুত ওসিআর স্ক্যান।',
      card1Tag: 'ওসিআর স্ক্যান',
      card1Action: 'স্ক্যান করুন',

      card2Title: 'লিঙ্ক পরীক্ষা',
      card2Desc: 'ভুয়ো বিনিয়োগ পোর্টাল ও ক্ষতিকর এপিকে ফাইল চিহ্নিতকরণ।',
      card2Tag: 'ডোমেন ও এসএসএল',
      card2Action: 'ইউআরএল যাচাই',

      card3Title: 'মেসেজ বিশ্লেষণ',
      card3Desc: 'বিদ্যুৎ বিল বা লটারির ভুয়ো মেসেজ সহজে শনাক্ত করুন।',
      card3Tag: 'ভাষা বিশ্লেষণ',
      card3Action: 'মেসেজ পেস্ট করুন',

      card4Title: 'ডিপফেক ও ভয়েস স্ক্যান',
      card4Desc: 'এআই তৈরি জাল অডিও ও ভয়েস কল শনাক্তকরণ।',
      card4Tag: 'ভয়েস স্পেকট্রাম',
      card4Action: 'অডিও পরীক্ষা',
    },
    verifyBar: {
      tag: 'দ্রুত যাচাইকরণ বার',
      title: 'সন্দেহজনক অনুরোধ এখনই পরীক্ষা করুন',
      privacy: 'জিরো সার্ভার স্টোরেজ • দ্রুত নিরাপত্তা যাচাই',
      placeholder: 'ইউপিআই আইডি, লিঙ্ক বা ফোন নম্বর পেস্ট করুন...',
      paste: 'পেস্ট',
      verifyBtn: 'যাচাই করুন',
      samplePrompt: 'নমুনা পরীক্ষা করুন:',
    },
    howItWorks: {
      tag: 'সুরক্ষা প্রক্রিয়া',
      title: 'সংজ্ঞান শিল্ড কীভাবে আপনাকে রক্ষা করে',
      subtitle: 'সাইবার প্রতারণা রুখতে ভারতীয় প্রযুক্তির এআই সুরক্ষা কবচ',
      step1Title: '১. ইনপুট দিন',
      step1Desc: 'সন্দেহজনক ইউপিআই বা লিঙ্ক এখানে পেস্ট করুন।',
      step2Title: '২. এআই বিশ্লেষণ',
      step2Desc: 'সেবি, এনপিসিআই ও ফ্রড ডেটাবেসের সাথে রিয়েল-টাইম ম্যাচিং।',
      step3Title: '৩. সুরক্ষা নির্দেশিকা',
      step3Desc: 'ঝুঁকি স্কোর ও ১৯৩০ নম্বরে অ্যাকাউন্ট ফ্রিজ করার নির্দেশিকা পান।',
    },
    threatRadar: {
      tag: 'লাইভ সাইবার সতর্কতা',
      title: 'সক্রিয় ভারত সাইবার ফ্রড সতর্কতা',
      subtitle: 'ভারতীয় সাইবার অপরাধ সমন্বয় কেন্দ্র (I4C) এর রিয়েল-টাইম তথ্য',
      alert1Title: 'ভুয়ো এসবিআই রিওয়ার্ড এপিকে',
      alert1Desc: 'ক্ষতিকর অ্যাপ ইনস্টল করিয়ে ব্যাংক তথ্য চুরির চেষ্টা।',
      alert2Title: 'টেলিগ্রাম পার্ট-টাইম জব স্ক্যাম',
      alert2Desc: 'ভিডিও লাইক করার নাম করে অর্থ আত্মসাতের ফাঁদ।',
      alert3Title: 'ডিজিটাল অ্যারেস্ট সিবিআই প্রতারণা',
      alert3Desc: 'পার্সেলে মাদক থাকার ভয় দেখিয়ে ভিডিও কলে অর্থ আদায়।',
    },
    helplineBanner: {
      goldenHour: 'গোল্ডেন আওয়ার: ২ ঘণ্টার মধ্যে অভিযোগ জানান',
      title: 'অনলাইন প্রতারণায় অর্থ হারিয়েছেন? এখনই 1930 ডায়াল করুন',
      desc: 'জাতীয় সাইবার অপরাধ পোর্টাল প্রাপকের অ্যাকাউন্ট ফ্রিজ করতে পারে।',
      callBtn: '1930 নম্বরে কল করুন',
      portalBtn: 'সরকারি পোর্টাল (MHA)',
    }
  },

  te: {
    slogan: 'సంజ్ఞాన్ షీల్డ్ • చెల్లించే ముందు ధృవీకరించండి',
    nav: {
      home: 'హోమ్',
      verify: 'ధృవీకరణ వర్క్‌స్పేస్',
      history: 'ఆడిట్ చరిత్ర',
      learn: 'అవగాహన పాఠాలు',
      report: 'మోసం ఫిర్యాదు',
      emergency: 'అత్యవసర 1930',
      verified: 'ధృవీకరించబడిన పౌరుడు',
      historyAction: 'ధృవీకరణ చరిత్ర',
      reportAction: 'ఫిర్యాదులు & ఎఫ్ఐఆర్',
      alertsAction: 'హెచ్చరికలు',
      signOut: 'లాగ్ అవుట్',
    },
    hero: {
      badge: 'ఏఐ ఆధారిత భారత్ సైబర్ రక్షణ కవచం',
      title: 'డబ్బు చెల్లించే ముందు సందేశాలు, లింకులు మరియు సలహాలను ధృవీకరించండి!',
      subtitle: 'సురక్షితమైన డిజిటల్ భారత్ కోసం అత్యాధునిక ఏఐ ధృవీకరణ వ్యవస్థ',
      desc: 'వాట్సాప్ సందేశాలు, టెలిగ్రామ్ ట్రేడింగ్ చిట్కాలు మరియు యుపిఐ ఐడీలను మోసపోకముందే ధృవీకరించండి.',
      startBtn: 'తనిఖీ ప్రారంభించండి',
      learnBtn: 'పాఠాలు చూడండి',
      stat1: '3.2 లక్షలకు పైగా స్కామ్‌ల నివారణ',
      stat2: '₹42 కోట్లు సురక్షితం',
      stat3: 'పౌరులకు 100% ఉచితం',
    },
    actions: {
      card1Title: 'స్క్రీన్‌షాట్ అప్‌లోడ్',
      card1Desc: 'వాట్సాప్ చాట్‌లు మరియు రసీదుల తక్షణ ఓసిఆర్ స్కానింగ్.',
      card1Tag: 'తక్షణ ఓసిఆర్',
      card1Action: 'పత్రం స్కాన్ చేయండి',

      card2Title: 'లింక్ తనిఖీ చేయండి',
      card2Desc: 'నకిలీ పెట్టుబడి పోర్టల్స్ మరియు హానికరమైన ఎపికెలను గుర్తించండి.',
      card2Tag: 'డొమైన్ తనిఖీ',
      card2Action: 'యుఆర్ఎల్ తనిఖీ చేయండి',

      card3Title: 'సందేశాన్ని విశ్లేషించండి',
      card3Desc: 'కరెంట్ బిల్లు మరియు లాటరీ నకిలీ ఎస్ఎంఎస్‌లను గుర్తించండి.',
      card3Tag: 'సందేశ విశ్లేషణ',
      card3Action: 'సందేశం అతికించండి',

      card4Title: 'డీప్‌ఫేక్ & వాయిస్ స్కాన్',
      card4Desc: 'ఏఐ సృష్టించిన నకిలీ వాయిస్ కాల్స్‌ను గుర్తించండి.',
      card4Tag: 'వాయిస్ స్పెక్ట్రమ్',
      card4Action: 'ఆడియో తనిఖీ చేయండి',
    },
    verifyBar: {
      tag: 'వేగవంతమైన ధృవీకరణ బార్',
      title: 'అనుమానాస్పద లావాదేవీని ఇప్పుడే తనిఖీ చేయండి',
      privacy: 'జీరో సర్వర్ నిల్వ • తక్షణ భద్రతా విశ్లేషణ',
      placeholder: 'యుపిఐ ఐడీ, లింక్ లేదా ఫోన్ నంబర్‌ను ఇక్కడ అతికించండి...',
      paste: 'అతికించండి',
      verifyBtn: 'ధృవీకరించండి',
      samplePrompt: 'నమూనాలను ప్రయత్నించండి:',
    },
    howItWorks: {
      tag: 'రక్షణ వ్యవస్థ',
      title: 'సంజ్ఞాన్ షీల్డ్ 3 దశల్లో మిమ్మల్ని ఎలా రక్షిస్తుంది',
      subtitle: 'ఆర్థిక మోసాలను నివారించే భారతీయ స్వదేశీ ఏఐ భద్రతా వ్యవస్థ',
      step1Title: '1. నమోదు చేయండి',
      step1Desc: 'అనుమానాస్పద యుపిఐ లేదా లింక్‌ను ఇక్కడ నమోదు చేయండి.',
      step2Title: '2. ఏఐ విశ్లేషణ',
      step2Desc: 'సెబీ, ఎన్‌పిసిఐ మరియు మోసాల డేటాబేస్‌తో తక్షణ విశ్లేషణ.',
      step3Title: '3. రక్షణ మార్గదర్శకాలు',
      step3Desc: 'రిస్క్ స్కోర్ మరియు 1930 బ్యాంక్ ఫ్రీజ్ సూచనలను పొందండి.',
    },
    threatRadar: {
      tag: 'లైవ్ సైబర్ హెచ్చరికలు',
      title: 'తాజా భారత్ సైబర్ మోసాల హెచ్చరికలు',
      subtitle: 'ఇండియన్ సైబర్ క్రైమ్ కోఆర్డినేషన్ సెంటర్ (I4C) లైవ్ అప్‌డేట్స్',
      alert1Title: 'నకిలీ ఎస్‌బీఐ రివార్డ్ ఎపికె',
      alert1Desc: 'ఎస్ఎంఎస్ ద్వారా నకిలీ యాప్ పంపి బ్యాంక్ వివరాలు దోచుకునే ప్రయత్నం.',
      alert2Title: 'టెలిగ్రామ్ పార్ట్‌టైమ్ జాబ్ స్కామ్',
      alert2Desc: 'వీడియో లైక్‌ల పేరుతో డబ్బులు కాజేసే భారీ మోసం.',
      alert3Title: 'డిజిటల్ అరెస్ట్ సిబిఐ ఫ్రాడ్',
      alert3Desc: 'పార్సిల్‌లో డ్రగ్స్ ఉన్నాయని బెదిరిస్తూ వీడియో కాల్స్‌లో వసూళ్లు.',
    },
    helplineBanner: {
      goldenHour: 'గోల్డెన్ అవర్: 2 గంటల్లోగా ఫిర్యాదు చేయండి',
      title: 'ఆన్‌లైన్ మోసంలో డబ్బు కోల్పోయారా? వెంటనే 1930 కి కాల్ చేయండి',
      desc: 'నేషనల్ సైబర్ క్రైమ్ పోర్టల్ మోసగాళ్ల ఖాతాలను వెంటనే ఫ్రీజ్ చేయగలదు.',
      callBtn: '1930 కి కాల్ చేయండి',
      portalBtn: 'అధికారిక పోర్టల్ (MHA)',
    }
  },

  ta: {
    slogan: 'சம்ஞான் ஷீல்டு • பணம் செலுத்தும் முன் சரிபார்க்கவும்',
    nav: {
      home: 'முகப்பு',
      verify: 'சரிபார்ப்பு தளம்',
      history: 'வரலாறு',
      learn: 'விழிப்புணர்வு பாடங்கள்',
      report: 'மோசடி புகார்',
      emergency: 'அவசரம் 1930',
      verified: 'சான்றளிக்கப்பட்ட குடிமகன்',
      historyAction: 'சரிபார்ப்பு வரலாறு',
      reportAction: 'புகார்கள் & எஃப்.ஐ.ஆர்',
      alertsAction: 'எச்சரிக்கைகள்',
      signOut: 'வெளியேறு',
    },
    hero: {
      badge: 'ஏஐ-இயங்கும் பாரத சைபர் பாதுகாப்பு கவசம்',
      title: 'பணம் செலுத்துவதற்கு முன் செய்திகள், இணைப்புகள் மற்றும் ஆலோசனைகளை சரிபார்க்கவும்!',
      subtitle: 'பாதுகாப்பான இந்தியாவிற்கான செயற்கை நுண்ணறிவு சரிபார்ப்பு கட்டமைப்பு',
      desc: 'வாட்ஸ்அப் ஃபார்வர்டுகள், டெலிகிராம் முதலீட்டு குழுக்கள் மற்றும் யுபிஐ ஐடிகளை ஏமாறுவதற்கு முன்பே சரிபார்க்கவும்.',
      startBtn: 'சரிபார்க்கத் தொடங்குங்கள்',
      learnBtn: 'பாடங்களை பார்க்கவும்',
      stat1: '3.2 லட்சம்+ மோசடிகள் தடுப்பு',
      stat2: '₹42 கோடி பாதுகாக்கப்பட்டது',
      stat3: 'குடிமக்களுக்கு 100% இலவசம்',
    },
    actions: {
      card1Title: 'ஸ்கிரீன்ஷாட் பதிவேற்றவும்',
      card1Desc: 'வாட்ஸ்அப் சாட்கள் மற்றும் போலி ரசீதுகளின் உடனடி ஓசிஆர் ஆய்வு.',
      card1Tag: 'உடனடி ஓசிஆர்',
      card1Action: 'ஸ்கேன் செய்க',

      card2Title: 'இணைப்பைச் சரிபார்க்கவும்',
      card2Desc: 'போலி முதலீட்டு தளங்கள் மற்றும் தீங்கிழைக்கும் ஏபிகே கோப்புகளைக் கண்டறியவும்.',
      card2Tag: 'டொமைன் சரிபார்ப்பு',
      card2Action: 'சரிபார்க்கவும்',

      card3Title: 'செய்தியைப் பகுப்பாய்வு செய்க',
      card3Desc: 'மின்சாரக் கட்டணம் மற்றும் லாட்டரி போலி குறுஞ்செய்திகளைக் கண்டறியவும்.',
      card3Tag: 'மொழி பகுப்பாய்வு',
      card3Action: 'செய்தியை ஒட்டுக',

      card4Title: 'டீப்ஃபேக் & குரல் ஆய்வு',
      card4Desc: 'ஏஐ உருவாக்கிய போலி குரல் அழைப்புகளைக் கண்டறியவும்.',
      card4Tag: 'குரல் அலைவரிசை',
      card4Action: 'ஆடியோ ஆய்வு',
    },
    verifyBar: {
      tag: 'விரைவான சரிபார்ப்பு தளம்',
      title: 'சந்தேகத்திற்கிடமான கோரிக்கையை உடனே சரிபார்க்கவும்',
      privacy: 'சர்வர் சேமிப்பு இல்லை • உடனடி பாதுகாப்பு பகுப்பாய்வு',
      placeholder: 'யுபிஐ ஐடி, இணைப்பு அல்லது தொலைபேசி எண்ணை இங்கே ஒட்டவும்...',
      paste: 'ஒட்டு',
      verifyBtn: 'சரிபார்க்கவும்',
      samplePrompt: 'மாதிரிகளை முயற்சிக்கவும்:',
    },
    howItWorks: {
      tag: 'பாதுகாப்பு கட்டமைப்பு',
      title: 'சம்ஞான் ஷீல்டு உங்களை எவ்வாறு பாதுகாக்கிறது',
      subtitle: 'சைபர் நிதி மோசடிகளைத் தடுக்கும் இந்திய ஏஐ தொழில்நுட்பம்',
      step1Title: '1. உள்ளிடவும்',
      step1Desc: 'சந்தேகத்திற்கிடமான யுபிஐ அல்லது இணைப்பை உள்ளிடவும்.',
      step2Title: '2. ஏஐ ஆய்வு',
      step2Desc: 'செபி, என்ஃபிசிஐ மற்றும் மோசடி பதிவேடுகளுடன் சரிபார்ப்பு.',
      step3Title: '3. பாதுகாப்பு வழிகாட்டல்',
      step3Desc: 'உடனடி ரிஸ்க் ஸ்கோர் மற்றும் 1930 வங்கி கணக்கு முடக்கம் வழிகாட்டல்.',
    },
    threatRadar: {
      tag: 'நேரலை சைபர் எச்சரிக்கைகள்',
      title: 'செயலில் உள்ள பாரத சைபர் எச்சரிக்கைகள்',
      subtitle: 'இந்திய சைபர் குற்ற ஒருங்கிணைப்பு மையம் (I4C) நேரலை தகவல்கள்',
      alert1Title: 'போலி எஸ்பிஐ ரிவார்டு ஏபிகே',
      alert1Desc: 'போலி செயலி மூலம் வங்கி விவரங்களைத் திருடும் முயற்சி.',
      alert2Title: 'டெலிகிராம் பார்ட்-டைம் வேலை மோசடி',
      alert2Desc: 'வீடியோ லைக் செய்யும் பெயரில் முதலீடு பெற்று ஏமாற்றும் மோசடி.',
      alert3Title: 'டிஜிட்டல் கைது சிபிஐ மோசடி',
      alert3Desc: 'பார்சலில் போதைப்பொருள் இருப்பதாக பயமுறுத்தி மிரட்டிப் பணம் பறித்தல்.',
    },
    helplineBanner: {
      goldenHour: 'கோல்டன் ஹவர்: 2 மணி நேரத்திற்குள் புகார் செய்யவும்',
      title: 'ஆன்லைன் மோசடியில் பணத்தை இழந்தீர்களா? உடனே 1930-ஐ டயல் செய்யவும்',
      desc: 'தேசிய சைபர் குற்ற போர்டல் குற்றவாளிகளின் வங்கி கணக்கை முடக்க முடியும்.',
      callBtn: '1930-க்கு அழைக்கவும்',
      portalBtn: 'அதிகாரப்பூர்வ தளம் (MHA)',
    }
  },

  gu: {
    slogan: 'સંજ્ઞાન શીલ્ડ • ચુકવણી કરતા પહેલા ચકાસો',
    nav: {
      home: 'હોમ',
      verify: 'ચકાસણી વર્કસ્પેસ',
      history: 'ઓડિટ ઇતિહાસ',
      learn: 'જાગૃતિ પાઠ',
      report: 'છેતરપિંડી રિપોર્ટ',
      emergency: 'ઇમરજન્સી 1930',
      verified: 'પ્રમાણિત નાગરિક',
      historyAction: 'ચકાસણી ઇતિહાસ',
      reportAction: 'નોંધાયેલ રિપોર્ટ અને એફઆઈઆર',
      alertsAction: 'એસએમએસ અને યુપીઆઈ ચેતવણી',
      signOut: 'સાઇન આઉટ',
    },
    hero: {
      badge: 'એઆઈ-સંચાલિત ભારત સાયબર સુરક્ષા કવચ',
      title: 'પૈસા ચૂકવતા પહેલા મેસેજ, લિંક અથવા રોકાણ સલાહ ચકાસો!',
      subtitle: 'સુરક્ષિત ગુજરાત અને ભારત માટે આર્ટિફિશિયલ ઇન્ટેલિજન્સ સુરક્ષા પ્રણાલી',
      desc: 'વોટ્સએપ મેસેજ, ટેલિગ્રામ ટ્રેડિંગ ગ્રુપ અને યુપીઆઈ આઈડી છેતરાયા પહેલા ચકાસો.',
      startBtn: 'ચકાસણી શરૂ કરો',
      learnBtn: 'પાઠ જુઓ',
      stat1: '3.2 લાખ+ ફ્રોડ અટકાવ્યા',
      stat2: '₹42 કરોડ બચાવ્યા',
      stat3: 'નાગરિકો માટે 100% મફત',
    },
    actions: {
      card1Title: 'સ્ક્રીનશોટ અપલોડ કરો',
      card1Desc: 'વોટ્સએપ ચેટ અને બનાવટી પહોંચની ઝડપી ઓસીઆર તપાસ.',
      card1Tag: 'ઝડપી ઓસીઆર',
      card1Action: 'દસ્તાવેજ સ્કેન કરો',

      card2Title: 'લિંક તપાસો',
      card2Desc: 'નકલી રોકાણ પોર્ટલ અને ખતરનાક એપીકે ડાઉનલોડ તપાસો.',
      card2Tag: 'ડોમેન વેરિફિકેશન',
      card2Action: 'યુઆરએલ ચકાસો',

      card3Title: 'મેસેજ તપાસો',
      card3Desc: 'લાઈટ બિલ અને લોટરીના નકલી એસએમએસ ઓળખો.',
      card3Tag: 'ભાષા વિશ્લેષણ',
      card3Action: 'મેસેજ પેસ્ટ કરો',

      card4Title: 'ડીપફેક અને વોઇસ સ્કેન',
      card4Desc: 'એઆઈ દ્વારા બનાવેલા નકલી અવાજ અને ઓડિયોની તપાસ.',
      card4Tag: 'વોઇસ સ્પેક્ટ્રમ',
      card4Action: 'ઓડિયો તપાસો',
    },
    verifyBar: {
      tag: 'ઝડપી ચકાસણી બાર',
      title: 'શંકાસ્પદ વ્યવહારની તરત જ તપાસ કરો',
      privacy: 'ઝીરો સર્વર સ્ટોરેજ • તાત્કાલિક સુરક્ષા ચકાસણી',
      placeholder: 'યુપીઆઈ આઈડી, લિંક અથવા મેસેજ અહીં પેસ્ટ કરો...',
      paste: 'પેસ્ટ કરો',
      verifyBtn: 'ચકાસણી કરો',
      samplePrompt: 'નમૂના તપાસો:',
    },
    howItWorks: {
      tag: 'સુરક્ષા પ્રક્રિયા',
      title: 'સંજ્ઞાન શીલ્ડ ૩ પગલાંમાં કેવી રીતે રક્ષણ આપે છે',
      subtitle: 'સાયબર છેતરપિંડી રોકવા માટે ભારતની એઆઈ સુરક્ષા પ્રણાલી',
      step1Title: '૧. વિગત દાખલ કરો',
      step1Desc: 'શંકાસ્પદ યુપીઆઈ અથવા લિંક અહીં પેસ્ટ કરો.',
      step2Title: '૨. એઆઈ વિશ્લેષણ',
      step2Desc: 'સેબી, એનપીસીઆઈ અને ફ્રોડ ડેટાબેઝ સાથે તુરંત સરખામણી.',
      step3Title: '૩. સુરક્ષા માર્ગદર્શન',
      step3Desc: 'તરત રિસ્ક સ્કોર અને ૧૯૩૦ બેંક ફ્રીઝ માર્ગદર્શન મેળવો.',
    },
    threatRadar: {
      tag: 'લાઈવ સાયબર ચેતવણી',
      title: 'સક્રિય ભારત સાયબર ચેતવણીઓ',
      subtitle: 'ભારતીય સાયબર ક્રાઈમ કોઓર્ડિનેશન સેન્ટર (I4C) રીઅલ-ટાઇમ અપડેટ્સ',
      alert1Title: 'નકલી એસબીઆઈ રિવોર્ડ એપીકે',
      alert1Desc: 'એસએમએસ દ્વારા નકલી એપ મોકલીને બેંક વિગતો ચોરવાનો પ્રયાસ.',
      alert2Title: 'ટેલિગ્રામ પાર્ટ-ટાઇમ જોબ સ્કેમ',
      alert2Desc: 'વિડિયો લાઈક કરવાના બહાને મોટી રકમ પડાવવાનું ષડયંત્ર.',
      alert3Title: 'ડિજિટલ એરેસ્ટ સીબીઆઈ ફ્રોડ',
      alert3Desc: 'પાર્સલમાં ડ્રગ્સ હોવાનો ડર બતાવીને વિડિયો કોલ પર તોડબાજી.',
    },
    helplineBanner: {
      goldenHour: 'ગોલ્ડન અવર: ૨ કલાકની અંદર ફરિયાદ કરો',
      title: 'ઓનલાઈન છેતરપિંડીમાં પૈસા ગુમાવ્યા? તરત જ 1930 ડાયલ કરો',
      desc: 'રાષ્ટ્રીય સાયબર પોર્ટલ છેતરપિંડી કરનારના ખાતાને તરત ફ્રીઝ કરી શકે છે.',
      callBtn: '1930 પર કૉલ કરો',
      portalBtn: 'સત્તાવાર પોર્ટલ (MHA)',
    }
  },

  kn: {
    slogan: 'ಸಂಜ್ಞಾನ್ ಶೀಲ್ಡ್ • ಹಣ ಪಾವತಿಸುವ ಮುನ್ನ ಪರಿಶೀಲಿಸಿ',
    nav: {
      home: 'ಮುಖಪುಟ',
      verify: 'ಪರಿಶೀಲನಾ ಕಾರ್ಯಕ್ಷೇತ್ರ',
      history: 'ಆಡಿಟ್ ಇತಿಹಾಸ',
      learn: 'ಜಾಗೃತಿ ಪಾಠಗಳು',
      report: 'ವಂಚನೆ ದೂರು',
      emergency: 'ತುರ್ತು 1930',
      verified: 'ದೃಢೀಕೃತ ನಾಗರಿಕ',
      historyAction: 'ಪರಿಶೀಲನೆ ಇತಿಹಾಸ',
      reportAction: 'ದೂರುಗಳು ಮತ್ತು ಎಫ್‌ಐಆರ್',
      alertsAction: 'ಎಚ್ಚರಿಕೆಗಳು',
      signOut: 'ಲಾಗ್ ಔಟ್',
    },
    hero: {
      badge: 'ಎಐ-ಚಾಲಿತ ಭಾರತ ಸೈಬರ್ ಭದ್ರತಾ ಕವಚ',
      title: 'ಹಣ ಪಾವತಿಸುವ ಮುನ್ನ ಸಂದೇಶ, ಲಿಂಕ್ ಅಥವಾ ಹೂಡಿಕೆ ಸಲಹೆ ಪರಿಶೀಲಿಸಿ!',
      subtitle: 'ಸುರಕ್ಷಿತ ಭಾರತಕ್ಕಾಗಿ ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ ಆಧಾರಿತ ಪರಿಶೀಲನಾ ವ್ಯವಸ್ಥೆ',
      desc: 'ವಂಚನೆಗೊಳಗಾಗುವ ಮುನ್ನವೇ ವಾಟ್ಸಾಪ್ ಸಂದೇಶಗಳು, ಟೆಲಿಗ್ರಾಂ ಹೂಡಿಕೆ ಗುಂಪುಗಳು ಮತ್ತು ಯುಪಿಐ ಐಡಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
      startBtn: 'ಪರಿಶೀಲನೆ ಪ್ರಾರಂಭಿಸಿ',
      learnBtn: 'ಪಾಠಗಳನ್ನು ನೋಡಿ',
      stat1: '3.2 ಲಕ್ಷ+ ವಂಚನೆ ತಡೆಗಟ್ಟಲಾಗಿದೆ',
      stat2: '₹42 ಕೋಟಿ ರಕ್ಷಿಸಲಾಗಿದೆ',
      stat3: 'ನಾಗರಿಕರಿಗೆ 100% ಉಚಿತ',
    },
    actions: {
      card1Title: 'ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      card1Desc: 'ವಾಟ್ಸಾಪ್ ಚಾಟ್‌ಗಳು ಮತ್ತು ರಶೀದಿಗಳ ತ್ವರಿತ ಒಸಿಆರ್ ಪರಿಶೀಲನೆ.',
      card1Tag: 'ತ್ವರಿತ ಒಸಿಆರ್',
      card1Action: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',

      card2Title: 'ಲಿಂಕ್ ಪರಿಶೀಲಿಸಿ',
      card2Desc: 'ನಕಲಿ ಹೂಡಿಕೆ ತಾಣಗಳು ಮತ್ತು ಅಪಾಯಕಾರಿ ಎಪಿಕೆಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಿ.',
      card2Tag: 'ಡೊಮೈನ್ ಪರಿಶೀಲನೆ',
      card2Action: 'ಯುಆರ್‌ಎಲ್ ಪರಿಶೀಲಿಸಿ',

      card3Title: 'ಸಂದೇಶ ವಿಶ್ಲೇಷಿಸಿ',
      card3Desc: 'ವಿದ್ಯುತ್ ಬಿಲ್ ಮತ್ತು ಲಾಟರಿ ನಕಲಿ ಸಂದೇಶಗಳನ್ನು ಸುಲಭವಾಗಿ ಗುರುತಿಸಿ.',
      card3Tag: 'ಭಾಷಾ ವಿಶ್ಲೇಷಣೆ',
      card3Action: 'ಸಂದೇಶ ಪೇಸ್ಟ್ ಮಾಡಿ',

      card4Title: 'ಡೀಪ್‌ಫೇಕ್ ಮತ್ತು ಧ್ವನಿ ಸ್ಕ್ಯಾನ್',
      card4Desc: 'ಎಐ ಸೃಷ್ಟಿಸಿದ ನಕಲಿ ಆಡಿಯೋ ಮತ್ತು ಧ್ವನಿ ಕರೆಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಿ.',
      card4Tag: 'ಧ್ವನಿ ಸ್ಪೆಕ್ಟ್ರಮ್',
      card4Action: 'ಆಡಿಯೋ ಪರೀಕ್ಷಿಸಿ',
    },
    verifyBar: {
      tag: 'ತ್ವರಿತ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ',
      title: 'ಅನುಮಾನಾಸ್ಪದ ವಹಿವಾಟನ್ನು ತಕ್ಷಣವೇ ಪರಿಶೀಲಿಸಿ',
      privacy: 'ಶೂನ್ಯ ಸರ್ವರ್ ಸಂಗ್ರಹಣೆ • ತ್ವರಿತ ಭದ್ರತಾ ಪರಿಶೀಲನೆ',
      placeholder: 'ಯುಪಿಐ ಐಡಿ, ಲಿಂಕ್ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ...',
      paste: 'ಪೇಸ್ಟ್',
      verifyBtn: 'ಪರಿಶೀಲಿಸಿ',
      samplePrompt: 'ಮಾದರಿಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ:',
    },
    howItWorks: {
      tag: 'ಭದ್ರತಾ ವ್ಯವಸ್ಥೆ',
      title: 'ಸಂಜ್ಞಾನ್ ಶೀಲ್ಡ್ 3 ಹಂತಗಳಲ್ಲಿ ನಿಮ್ಮನ್ನು ಹೇಗೆ ರಕ್ಷಿಸುತ್ತದೆ',
      subtitle: 'ಸೈಬರ್ ಆರ್ಥಿಕ ವಂಚನೆಗಳನ್ನು ತಡೆಗಟ್ಟುವ ಭಾರತೀಯ ಎಐ ತಂತ್ರಜ್ಞಾನ',
      step1Title: '1. ನಮೂದಿಸಿ',
      step1Desc: 'ಅನುಮಾನಾಸ್ಪದ ಯುಪಿಐ ಅಥವಾ ಲಿಂಕ್ ಅನ್ನು ಇಲ್ಲಿ ನಮೂದಿಸಿ.',
      step2Title: '2. ಎಐ ವಿಶ್ಲೇಷಣೆ',
      step2Desc: 'ಸೆಬಿ, ಎನ್‌ಪಿಸಿಐ ಮತ್ತು ವಂಚನೆ ಡೇಟಾಬೇಸ್‌ನೊಂದಿಗೆ ತ್ವರಿತ ಪರಿಶೀಲನೆ.',
      step3Title: '3. ಭದ್ರತಾ ಮಾರ್ಗದರ್ಶನ',
      step3Desc: 'ತಕ್ಷಣದ ರಿಸ್ಕ್ ಸ್ಕೋರ್ ಮತ್ತು 1930 ಬ್ಯಾಂಕ್ ಫ್ರೀಜ್ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.',
    },
    threatRadar: {
      tag: 'ಲೈವ್ ಸೈಬರ್ ಎಚ್ಚರಿಕೆಗಳು',
      title: 'ಸಕ್ರಿಯ ಭಾರತ ಸೈಬರ್ ಎಚ್ಚರಿಕೆಗಳು',
      subtitle: 'ಭಾರತೀಯ ಸೈಬರ್ ಅಪರಾಧ ಸಮನ್ವಯ ಕೇಂದ್ರದ (I4C) ಲೈವ್ ಅಪ್‌ಡೇಟ್‌ಗಳು',
      alert1Title: 'ನಕಲಿ ಎಸ್‌ಬಿಐ ರಿವಾರ್ಡ್ ಎಪಿಕೆ',
      alert1Desc: 'ಎಸ್ಎಂಎಸ್ ಮೂಲಕ ನಕಲಿ ಆ್ಯಪ್ ಕಳುಹಿಸಿ ಬ್ಯಾಂಕ್ ವಿವರ ಕದಿಯುವ ಯತ್ನ.',
      alert2Title: 'ಟೆಲಿಗ್ರಾಂ ಪಾರ್ಟ್-ಟೈಮ್ ಜಾಬ್ ಸ್ಕ್ಯಾಮ್',
      alert2Desc: 'ವಿಡಿಯೋ ಲೈಕ್ ಹೆಸರಿನಲ್ಲಿ ಹಣ ವಂಚಿಸುವ ಜಾಲ.',
      alert3Title: 'ಡಿಜಿಟಲ್ ಅರೆಸ್ಟ್ ಸಿಬಿಐ ಫ್ರಾಡ್',
      alert3Desc: 'ಪಾರ್ಸೆಲ್‌ನಲ್ಲಿ ಮಾದಕವಸ್ತು ಇದೆ ಎಂದು ಹೆದರಿಸಿ ವಿಡಿಯೋ ಕರೆ ಮೂಲಕ ಹಣ ವಸೂಲಿ.',
    },
    helplineBanner: {
      goldenHour: 'ಗೋಲ್ಡನ್ ಅವರ್: 2 ಗಂಟೆಗಳ ಒಳಗೆ ದೂರು ದಾಖಲಿಸಿ',
      title: 'ಆನ್‌ಲೈನ್ ವಂಚನೆಯಲ್ಲಿ ಹಣ ಕಳೆದುಕೊಂಡಿದ್ದೀರಾ? ತಕ್ಷಣವೇ 1930 ಗೆ ಕರೆ ಮಾಡಿ',
      desc: 'ರಾಷ್ಟ್ರೀಯ ಸೈಬರ್ ಪೋರ್ಟಲ್ ವಂಚಕರ ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ತಕ್ಷಣವೇ ಸ್ಥಗಿತಗೊಳಿಸಬಹುದು.',
      callBtn: '1930 ಗೆ ಕರೆ ಮಾಡಿ',
      portalBtn: 'ಅಧಿಕೃತ ಪೋರ್ಟಲ್ (MHA)',
    }
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('sangyan_lang') || 'hi'
  })

  const setLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode)
      localStorage.setItem('sangyan_lang', langCode)
    }
  }

  const t = TRANSLATIONS[currentLang] || TRANSLATIONS.en

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
