import { createContext, useContext, useState, useEffect } from 'react'

export const LANGUAGES = [
  { code: 'hi', label: 'हिन्दी', sub: 'Hindi' },
  { code: 'en', label: 'English', sub: 'English' },
  { code: 'mr', label: 'मराठी', sub: 'Marathi' },
  { code: 'bn', label: 'বাংলা', sub: 'Bengali' },
  { code: 'te', label: 'తెలుగు', sub: 'Telugu' },
  { code: 'ta', label: 'தமிழ்', sub: 'Tamil' },
  { code: 'gu', label: 'ગુજરાતી', sub: 'Gujarati' },
  { code: 'kn', label: 'ಕನ್ನಡ', sub: 'Kannada' },
]

export const TRANSLATIONS = {
  "hi": {
    "slogan": "संज्ञान शील्ड • धोखाधड़ी से पहले संज्ञान",
    "nav": {
      "home": "होम",
      "verify": "सत्यापन वर्कस्पेस",
      "history": "ऑडिट इतिहास",
      "learn": "जागरूकता पाठ",
      "report": "धोखाधड़ी रिपोर्ट",
      "emergency": "आपातकालीन 1930",
      "verified": "प्रमाणित नागरिक",
      "historyAction": "सत्यापन इतिहास",
      "reportAction": "दर्ज रिपोर्ट व एफआईआर",
      "alertsAction": "एसएमएस व यूपीआई अलर्ट",
      "signOut": "लॉग आउट / पहचान बदलें"
    },
    "hero": {
      "badge": "एआई-संचालित भारत साइबर सुरक्षा कवच",
      "title": "संदेश, लिंक या निवेश सलाह की जांच करें धोखाधड़ी से पहले!",
      "subtitle": "सुरक्षित और सशक्त भारत के लिए एआई-संचालित संज्ञान प्रणाली",
      "desc": "व्हाट्सएप फॉरवर्ड, टेलीग्राम ट्रेडिंग ग्रुप, सेबी पंजीकरण और यूपीआई हैंडल की तुरंत जांच करें। हर नागरिक के लिए निःशुल्क शून्य-ट्रस्ट सुरक्षा।",
      "startBtn": "सत्यापन शुरू करें",
      "learnBtn": "जागरूकता पाठ देखें",
      "stat1": "3.2 लाख+ फ्रॉड रोके गए",
      "stat2": "₹42 करोड़ की बचत",
      "stat3": "नागरिकों के लिए 100% निःशुल्क"
    },
    "actions": {
      "card1Title": "स्क्रीनशॉट अपलोड करें",
      "card1Desc": "व्हाट्सएप चैट, फर्जी रसीद और टेलीग्राम संदेशों की तत्काल ओसीआर जांच।",
      "card1Tag": "त्वरित ओसीआर",
      "card1Action": "दस्तावेज़ स्कैन करें",
      "card2Title": "संदिग्ध लिंक जांचें",
      "card2Desc": "फर्जी निवेश पोर्टल, एपीके डाउनलोड और फ़िशिंग डोमेन की त्वरित जांच।",
      "card2Tag": "डोमेन व एसएसएल",
      "card2Action": "यूआरएल जांचें",
      "card3Title": "एसएमएस / संदेश जांचें",
      "card3Desc": "बिजली बिल, लॉटरी और बैंक अपडेट के फर्जी संदेशों की पहचान करें।",
      "card3Tag": "एनएलपी भाषा विश्लेषण",
      "card3Action": "संदेश चिपकाएं",
      "card4Title": "डीपफेक व वॉइस जांच",
      "card4Desc": "आर्टिफिशियल इंटेलिजेंस द्वारा बनाई गई फर्जी आवाज और ऑडियो की पहचान।",
      "card4Tag": "वॉइस स्पेक्ट्रम",
      "card4Action": "ऑडियो जांचें"
    },
    "verifyBar": {
      "tag": "त्वरित बहु-मोडल सत्यापन बार",
      "title": "संदिग्ध अनुरोध की तुरंत जांच करें",
      "privacy": "शून्य सर्वर स्टोरेज • तत्काल क्रिप्टोग्राफ़िक हैश जांच",
      "placeholder": "यूपीआई आईडी, लिंक, फोन नंबर या संदेश यहाँ चिपकाएँ...",
      "paste": "पेस्ट करें",
      "verifyBtn": "सत्यापन जांचें",
      "samplePrompt": "नमूना परीक्षण करें:",
      "safeTitle": "सत्यापित सुरक्षित संस्था (Verified Safe)",
      "safeDesc": "आधिकारिक सेबी/एनपीसीआई निर्देशिका में सत्यापित। संबंधित खाता सुरक्षित बैंक गेटवे से जुड़ा है।",
      "dangerTitle": "उच्च साइबर जोखिम अलर्ट (High Fraud Signal)",
      "dangerDesc": "चेतावनी: यह पहचान 1930 साइबर हेल्पलाइन पर पूर्व में दर्ज शिकायतों से मेल खाती है। कोई भुगतान न करें!",
      "reportBtn": "शिकायत दर्ज करें",
      "auditBtn": "विस्तृत फॉरेंसिक विश्लेषण"
    },
    "howItWorks": {
      "tag": "सुरक्षा प्रक्रिया",
      "title": "संज्ञान शील्ड 3 चरणों में कैसे रक्षा करता है",
      "subtitle": "जटिल साइबर वित्तीय धोखाधड़ी को सेकंडों में पहचानने वाली तकनीक",
      "step1Title": "1. इनपुट दें",
      "step1Desc": "संदिग्ध यूपीआई आईडी, लिंक, स्क्रीनशॉट या संदेश चिपकाएं।",
      "step2Title": "2. एआई सत्यापन",
      "step2Desc": "सेबी, एनपीसीआई और साइबर अपराध रजिस्ट्री से मिलान कर जोखिम का विश्लेषण।",
      "step3Title": "3. स्पष्ट सुरक्षा निर्देश",
      "step3Desc": "तुरंत सुरक्षा स्कोर, 1930 फ्रॉड फ्रीज निर्देश व एफआईआर साक्ष्य सारांश प्राप्त करें।"
    },
    "threatRadar": {
      "tag": "लाइव थ्रेट टेलीमेट्री",
      "title": "सक्रिय भारत साइबर फ्रॉड अलर्ट",
      "subtitle": "भारतीय साइबर अपराध समन्वय केंद्र (I4C) के सहयोग से रीयल-टाइम अपडेट",
      "alert1Title": "फर्जी एसबीआई रिवॉर्ड एपीके",
      "alert1Desc": "एसएमएस के जरिए एपीके लिंक भेजकर बैंक ओटीपी चुराने का प्रयास।",
      "alert2Title": "टेलीग्राम पार्ट-टाइम जॉब स्कैम",
      "alert2Desc": "यूट्यूब वीडियो लाइक करने के नाम पर दैनिक मुनाफे का झांसा।",
      "alert3Title": "डिजिटल अरेस्ट सीबीआई फ्रॉड",
      "alert3Desc": "पार्सल में नशीले पदार्थ मिलने का डर दिखाकर वीडियो कॉल पर जबरन वसूली।"
    },
    "helplineBanner": {
      "goldenHour": "गोल्डन ऑवर प्रोटोकॉल: 2 घंटे के भीतर कार्रवाई",
      "title": "ऑनलाइन धोखाधड़ी में पैसे गंवाए? तुरंत 1930 डायल करें",
      "desc": "राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल (I4C) लाभार्थी बैंक खातों को तत्काल फ्रीज कर सकता है।",
      "callBtn": "1930 पर कॉल करें",
      "portalBtn": "आधिकारिक पोर्टल (MHA)",
      "dossierBtn": "एफआईआर डोजियर बनाएं"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "होम",
      "breadcrumbWorkspace": "नागरिक सत्यापन वर्कस्पेस",
      "engineVersion": "एआई शील्ड इंजन v4.2",
      "registryConnected": "सेबी व एनपीसीआई रजिस्ट्री: कनेक्टेड",
      "ramProcessed": "100% रैम प्रोसेस्ड",
      "title": "भुगतान से पहले संज्ञान लें",
      "subtitle": "किसी भी निवेश सलाह, टेलीग्राम टिप, या यूपीआई भुगतान की जांच करें।",
      "tabScreenshot": "स्क्रीनशॉट",
      "tabLink": "लिंक / डोमेन",
      "tabMessage": "संदेश",
      "tabVoice": "वॉइस / ऑडियो",
      "dropzoneTitle": "स्क्रीनशॉट यहां खींचें और छोड़ें, या",
      "browseFiles": "फ़ाइलें चुनें",
      "dropzoneHint": "(जेपीजी, पीएनजी, व्हाट्सएप चैट, टेलीग्राम स्क्रीनशॉट 10 एमबी तक)",
      "ocrTag": "ओसीआर टेक्स्ट निष्कर्षण",
      "qrTag": "यूपीआई क्यूआर / आईडी पार्सिंग",
      "sealTag": "फर्जी मुहर पहचान",
      "sampleHeading": "पूर्व-लोडेड भारतीय फ्रॉड नमूनों से त्वरित जांच करें:",
      "clickToTest": "परीक्षण के लिए किसी पर भी क्लिक करें",
      "linkLabel": "जांच के लिए वेबसाइट लिंक या डोमेन दर्ज करें:",
      "linkPlaceholder": "उदा. https://fake-investment-fund.in या telegram.me/vip_calls",
      "inspectUrlBtn": "डोमेन व एसएसएल जांचें",
      "messageLabel": "संदिग्ध संदेश, एसएमएस या व्हाट्सएप टेक्स्ट चिपकाएं:",
      "messagePlaceholder": "बिजली बिल कटने की चेतावनी, लॉटरी संदेश, वर्क फ्रॉम होम जॉब ऑफर...",
      "inspectMsgBtn": "एआई टेक्स्ट फॉरेंसिक चलाएं",
      "voiceTitle": "कॉल रिकॉर्डिंग या ऑडियो नोट अपलोड / रिकॉर्ड करें",
      "voiceDesc": "डीपफेक क्लोन व धमकी भरी आवाज की स्पेक्ट्रम जांच।",
      "startRecord": "रिकॉर्डिंग शुरू करें",
      "stopRecord": "रिकॉर्डिंग रोकें",
      "uploadAudio": "ऑडियो फ़ाइल अपलोड करें",
      "analyzing": "एआई फॉरेंसिक विश्लेषण जारी है...",
      "analyzingSub": "सेबी, एनपीसीआई और आई4सी साइबर रजिस्ट्री से मिलान किया जा रहा है...",
      "fullAuditBtn": "विस्तृत फॉरेंसिक रिपोर्ट बनाएं"
    },
    "footer": {
      "advisoryTitle": "आधिकारिक सलाह:",
      "advisoryText": "संज्ञान शील्ड निवेश सलाह नहीं देता। हम धन हस्तांतरण से पहले पहचान, पंजीकरण और धोखाधड़ी पैटर्न की स्वतंत्र पुष्टि करते हैं।",
      "brandDesc": "भारत के लिए राष्ट्रीय नागरिक फिनटेक एआई सत्यापन शील्ड। यूपीआई घोटालों, फर्जी ऐप्स और सोशल इंजीनियरिंग से रीयल-टाइम सुरक्षा।",
      "confidentialBadge": "100% गोपनीय • भारत के लिए निर्मित • शून्य डेटा बिक्री",
      "portalsHeading": "संस्थागत पोर्टल",
      "navHeading": "त्वरित नेविगेशन",
      "helplineHeading": "आपातकालीन सहायता",
      "rights": "सर्वाधिकार सुरक्षित। नागरिक साइबर सुरक्षा पहल।"
    }
  },
  "en": {
    "slogan": "Sangyan Shield • Verify Before You Pay",
    "nav": {
      "home": "Home",
      "verify": "Verify Workspace",
      "history": "Audit History",
      "learn": "Learn (Micro-Lessons)",
      "report": "Report Fraud",
      "emergency": "Emergency 1930",
      "verified": "Verified Citizen",
      "historyAction": "Verification History",
      "reportAction": "Reported Frauds & FIR Drafts",
      "alertsAction": "SMS & UPI Alert Push",
      "signOut": "Sign Out / Switch Identity"
    },
    "hero": {
      "badge": "AI-POWERED BHARAT CYBER DEFENSE",
      "title": "Verify Before You Pay — Protect Against Deepfakes & UPI Fraud!",
      "subtitle": "Sovereign AI Verification Infrastructure for a Safer & Smarter India",
      "desc": "Verify WhatsApp forwards, Telegram trading tips, SEBI numbers, and UPI handles before making any transaction. Instant zero-trust telemetry for every citizen.",
      "startBtn": "Start Checking",
      "learnBtn": "Explore Lessons",
      "stat1": "3.2 Lakh+ Scams Flagged",
      "stat2": "₹42 Cr Protected",
      "stat3": "100% Free for Citizens"
    },
    "actions": {
      "card1Title": "Upload Screenshot",
      "card1Desc": "Instant OCR scanning of WhatsApp chats, forged receipts, and Telegram tips.",
      "card1Tag": "Instant OCR",
      "card1Action": "Scan Document",
      "card2Title": "Check a Link",
      "card2Desc": "Inspect suspicious investment portals, fake APK downloads, and phishing domains.",
      "card2Tag": "Domain & SSL",
      "card2Action": "Analyze URL",
      "card3Title": "Paste Message",
      "card3Desc": "Detect Ponzi schemes, fake job offers, and guaranteed return traps.",
      "card3Tag": "NLP Fraud Model",
      "card3Action": "Inspect Text",
      "card4Title": "Deepfake & Voice",
      "card4Desc": "Inspect extortion call audio notes and AI deepfake cloned voices.",
      "card4Tag": "Voice Spectrum",
      "card4Action": "Analyze Audio"
    },
    "verifyBar": {
      "tag": "FAST MULTI-MODAL VERIFICATION BAR",
      "title": "Verify Suspicious Request Now",
      "privacy": "Zero Server Storage • Instant Cryptographic Hash Check",
      "placeholder": "Paste UPI ID, Link, Phone, or Message here...",
      "paste": "Paste",
      "verifyBtn": "Verify Integrity",
      "samplePrompt": "Try test samples:",
      "safeTitle": "Verified Entity (Safe)",
      "safeDesc": "Active SEBI / NPCI registry confirmation. Account linked to verified clearing house gateway.",
      "dangerTitle": "High Threat Signal Detected",
      "dangerDesc": "Warning: Entity matched against 18 prior fraud complaints on National Helpline 1930.",
      "reportBtn": "Report Immediately",
      "auditBtn": "Full Forensic Audit"
    },
    "howItWorks": {
      "tag": "DEFENSE PIPELINE",
      "title": "How Sangyan Shield Protects in 3 Steps",
      "subtitle": "Advanced AI telemetry transforming complex fraud intelligence into instant citizen protection.",
      "step1Title": "1. Ingest Input",
      "step1Desc": "Paste suspect UPI, domain, OCR screenshot, SMS text, or call audio.",
      "step2Title": "2. Multi-Registry AI Cross-Match",
      "step2Desc": "Live checks across SEBI directories, NPCI registries, and I4C databases.",
      "step3Title": "3. Actionable Defense Verdict",
      "step3Desc": "Instant 0-100 risk score, 1930 fund-freeze instructions, and downloadable FIR dossier."
    },
    "threatRadar": {
      "tag": "LIVE THREAT RADAR",
      "title": "Active Bharat Cyber Fraud Radar",
      "subtitle": "Real-time telemetry synchronized with Indian Cyber Crime Coordination Centre (I4C)",
      "alert1Title": "Fake SBI Rewards APK",
      "alert1Desc": "Phishing SMS distributing malicious APK to intercept OTPs and bank credentials.",
      "alert2Title": "Telegram Part-Time Task Scam",
      "alert2Desc": "Fraudsters promising ₹3,500 daily for liking videos, asking for upfront task deposit.",
      "alert3Title": "Digital Arrest CBI Fraud",
      "alert3Desc": "Video call extortion claiming contraband detected in international parcel."
    },
    "helplineBanner": {
      "goldenHour": "GOLDEN HOUR PROTOCOL: ACT WITHIN 2 HOURS",
      "title": "Lost Money to Online Fraud? Dial 1930 Immediately",
      "desc": "National Cyber Crime Portal (I4C) can freeze beneficiary accounts before funds are laundered.",
      "callBtn": "Call 1930 Now",
      "portalBtn": "Official Portal (MHA)",
      "dossierBtn": "Generate FIR Dossier"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "Home",
      "breadcrumbWorkspace": "Civic Verification Workspace",
      "engineVersion": "AI Shield Engine v4.2",
      "registryConnected": "SEBI & NPCI Threat Registry: Connected",
      "ramProcessed": "100% RAM Processed",
      "title": "Verify Before You Pay",
      "subtitle": "Paste, upload, or speak the details of any investment advice, telegram tip, or payment request.",
      "tabScreenshot": "Screenshot",
      "tabLink": "Link / Domain",
      "tabMessage": "Message",
      "tabVoice": "Voice / Audio",
      "dropzoneTitle": "Drag and drop your screenshot here, or",
      "browseFiles": "Browse Files",
      "dropzoneHint": "(JPG, PNG, WhatsApp chats, Telegram channels, SMS captures up to 10MB)",
      "ocrTag": "OCR Text Extraction",
      "qrTag": "UPI QR / ID Parsing",
      "sealTag": "Forged Seal Detection",
      "sampleHeading": "Or Quick Test with Preloaded Indian Scam Samples:",
      "clickToTest": "Click any to test engine",
      "linkLabel": "Enter Website Link or Domain to inspect:",
      "linkPlaceholder": "e.g. https://fake-investment-fund.in or telegram.me/vip_calls",
      "inspectUrlBtn": "Inspect Domain & SSL",
      "messageLabel": "Paste suspicious message, SMS or WhatsApp text:",
      "messagePlaceholder": "Electricity bill warning, lottery win message, work-from-home job offer...",
      "inspectMsgBtn": "Run AI Text Forensics",
      "voiceTitle": "Upload or Record Call Audio Note",
      "voiceDesc": "Detect synthetic deepfake clones, voice modulation, and extortion threats.",
      "startRecord": "Start Recording",
      "stopRecord": "Stop Recording",
      "uploadAudio": "Upload Audio Clip",
      "analyzing": "AI Forensic Analysis in progress...",
      "analyzingSub": "Querying SEBI, NPCI and I4C databases...",
      "fullAuditBtn": "Generate Full Forensic Report"
    },
    "footer": {
      "advisoryTitle": "Official Advisory:",
      "advisoryText": "Sangyan Shield does NOT give investment advice or predict returns. We independently verify identity, credentials, and scam patterns before you transfer money.",
      "brandDesc": "National Civic Fintech AI Verification Shield for India. Real-time protection against UPI scams, fake investment apps, social engineering threats, and fraudulent sender handles.",
      "confidentialBadge": "100% Confidential • Built for Bharat • Zero Data Selling",
      "portalsHeading": "Institutional Portals",
      "navHeading": "Quick Navigation",
      "helplineHeading": "Emergency Help",
      "rights": "All rights reserved. Civic Cyber Defense Initiative."
    }
  },
  "mr": {
    "slogan": "संज्ञान शील्ड • पैसे देण्यापूर्वी खात्री करा",
    "nav": {
      "home": "मुख्यपृष्ठ",
      "verify": "पडताळणी वर्कस्पेस",
      "history": "ऑडिट इतिहास",
      "learn": "जागरूकता धडे",
      "report": "फसवणूक तक्रार",
      "emergency": "तातडीची मदत 1930",
      "verified": "प्रमाणित नागरिक",
      "historyAction": "पडताळणी इतिहास",
      "reportAction": "नोंदवलेल्या तक्रारी व एफआयआर",
      "alertsAction": "एसएमएस व यूपीआय सतर्कता",
      "signOut": "बाहेर पडा / खाते बदला"
    },
    "hero": {
      "badge": "एआय-सक्षम भारत सायबर सुरक्षा कवच",
      "title": "पैसे पाठवण्यापूर्वी संदेश, लिंक किंवा गुंतवणुकीची खात्री करा!",
      "subtitle": "सुरक्षित आणि सक्षम भारतासाठी स्वदेशी एआय पडताळणी यंत्रणा",
      "desc": "व्हॉट्सअ‍ॅप फॉरवर्ड, टेलिग्राम ट्रेडिंग टिप्स, सेबी नोंदणी आणि यूपीआय हँडल्स त्वरित तपासा. प्रत्येक नागरिकासाठी १००% विनामूल्य सुरक्षा.",
      "startBtn": "पडताळणी सुरू करा",
      "learnBtn": "जागरूकता धडे पहा",
      "stat1": "३.२ लाख+ फसवणुका रोखल्या",
      "stat2": "₹४२ कोटींचे रक्षण",
      "stat3": "नागरिकांसाठी १००% मोफत"
    },
    "actions": {
      "card1Title": "स्क्रीनशॉट अपलोड करा",
      "card1Desc": "व्हॉट्सअ‍ॅप चॅट, बनावट पावत्या आणि टेलिग्राम संदेशांची झटपट ओसीआर तपासणी.",
      "card1Tag": "झटपट ओसीआर",
      "card1Action": "कागदपत्र स्कॅन करा",
      "card2Title": "संशयास्पद लिंक तपासा",
      "card2Desc": "बनावट गुंतवणूक पोर्टल्स, संशयास्पद एपीके आणि फिशिंग डोमेनची त्वरित तपासणी.",
      "card2Tag": "डोमेन व एसएसएल",
      "card2Action": "यूआरएल तपासा",
      "card3Title": "संदेश तपासा",
      "card3Desc": "लाइट बिल, लॉटरी व बनावट नोकरीच्या आमिषांची एआय तपासणी.",
      "card3Tag": "भाषा विश्लेषण",
      "card3Action": "संदेश पेस्ट करा",
      "card4Title": "डीपफेक व ऑडिओ तपासणी",
      "card4Desc": "एआय द्वारे तयार केलेला बनावट आवाज आणि धमकीचे कॉल ओळखा.",
      "card4Tag": "व्हॉइस स्पेक्ट्रम",
      "card4Action": "ऑडिओ तपासा"
    },
    "verifyBar": {
      "tag": "जलद बहु-माध्यम पडताळणी बार",
      "title": "संशयास्पद व्यवहाराची त्वरित खात्री करा",
      "privacy": "शून्य सर्व्हर स्टोरेज • त्वरित क्रिप्टोग्राफिक हॅश तपासणी",
      "placeholder": "यूपीआय आयडी, लिंक, फोन नंबर किंवा संदेश येथे पेस्ट करा...",
      "paste": "पेस्ट करा",
      "verifyBtn": "पडताळणी करा",
      "samplePrompt": "नमुना चाचणी करा:",
      "safeTitle": "सत्यापित सुरक्षित संस्था (Verified Safe)",
      "safeDesc": "अधिकृत सेबी/एनपीसीआय निर्देशिकेत नोंदणीकृत. बँक पेमेंट गेटवे सुरक्षित आहे.",
      "dangerTitle": "उच्च सायबर फसवणूक अलर्ट (High Fraud Signal)",
      "dangerDesc": "सावधान: ही माहिती १९३० सायबर हेल्पलाइनवर आधी नोंदवलेल्या तक्रारींशी जुळत आहे. पैसे पाठवू नका!",
      "reportBtn": "तक्रार नोंदवा",
      "auditBtn": "सविस्तर फॉरेन्सिक तपासणी"
    },
    "howItWorks": {
      "tag": "संरक्षण पद्धती",
      "title": "संज्ञान शील्ड ३ टप्प्यांत कशी रक्षा करते",
      "subtitle": "गुंतागुंतीची सायबर फसवणूक सेकंदात ओळखणारे स्वदेशी तंत्रज्ञान",
      "step1Title": "१. माहिती द्या",
      "step1Desc": "संशयास्पद यूपीआय, लिंक, स्क्रीनशॉट किंवा ऑडिओ पेस्ट करा.",
      "step2Title": "२. एआय पडताळणी",
      "step2Desc": "सेबी, एनपीसीआय आणि सायबर गुन्हे डेटाबेसशी थेट पडताळणी.",
      "step3Title": "३. त्वरित सुरक्षा निर्णय",
      "step3Desc": "सुरक्षा स्कोअर, १९३० खाते गोठवण्याची प्रक्रिया व एफआयआर पुरावा अहवाल मिळवा."
    },
    "threatRadar": {
      "tag": "थेट सायबर रडार",
      "title": "सक्रिय भारत सायबर फसवणूक अलर्ट",
      "subtitle": "भारतीय सायबर गुन्हे समन्वय केंद्र (I4C) च्या सहकार्याने थेट अपडेट",
      "alert1Title": "बनावट एसबीआय रिवॉर्ड एपीके",
      "alert1Desc": "एसएमएसद्वारे बनावट अ‍ॅप पाठवून बँकेचा ओटीपी चोरण्याचा प्रयत्न.",
      "alert2Title": "टेलिग्राम पार्ट-टाईम जॉब स्कॅम",
      "alert2Desc": "व्हिडिओ लाईक केल्यावर दररोज ₹३,५०० कमवण्याचे आमिष दाखवून फसवणूक.",
      "alert3Title": "डिजिटल अरेस्ट सीबीआय स्कॅम",
      "alert3Desc": "पार्सलमध्ये अमली पदार्थ सापडल्याची भीती दाखवून व्हिडिओ कॉलवर खंडणी."
    },
    "helplineBanner": {
      "goldenHour": "गोल्डन अव्हर: २ तासांच्या आत तक्रार नोंदवा",
      "title": "ऑनलाइन फसवणुकीत पैसे गेले? त्वरित १९३० वर कॉल करा",
      "desc": "राष्ट्रीय सायबर पोर्टल फसवणूक करणाऱ्याचे बँक खाते त्वरित गोठवू शकते.",
      "callBtn": "१९३० वर कॉल करा",
      "portalBtn": "अधिकृत पोर्टल (MHA)",
      "dossierBtn": "एफआयआर अहवाल तयार करा"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "मुख्यपृष्ठ",
      "breadcrumbWorkspace": "नागरिक पडताळणी वर्कस्पेस",
      "engineVersion": "एआय शील्ड इंजिन v4.2",
      "registryConnected": "सेबी व एनपीसीआय नोंदणी: जोडलेले आहे",
      "ramProcessed": "१००% रॅम सुरक्षित प्रक्रिया",
      "title": "पैसे देण्यापूर्वी खात्री करा",
      "subtitle": "गुंतवणूक सल्ला, टेलिग्राम टिप किंवा यूपीआय व्यवहाराची सत्यता त्वरित तपासा.",
      "tabScreenshot": "स्क्रीनशॉट",
      "tabLink": "लिंक / डोमेन",
      "tabMessage": "संदेश",
      "tabVoice": "व्हॉइस / ऑडिओ",
      "dropzoneTitle": "स्क्रीनशॉट येथे ड्रॅग करून टाका, किंवा",
      "browseFiles": "फाइल निवडा",
      "dropzoneHint": "(जेपीजी, पीएनजी, व्हॉट्सअ‍ॅप चॅट, टेलिग्राम स्क्रीनशॉट १० एमबी पर्यंत)",
      "ocrTag": "ओसीआर मजकूर तपासणी",
      "qrTag": "यूपीआय क्यूआर कोड पार्सिंग",
      "sealTag": "बनावट शिक्का शोध",
      "sampleHeading": "किंवा आधीच लोड केलेल्या भारतीय फसवणूक नमुन्यांवर चाचणी घ्या:",
      "clickToTest": "चाचणी घेण्यासाठी कोणत्याही नमुन्यावर क्लिक करा",
      "linkLabel": "तपासण्यासाठी वेबसाइट लिंक किंवा डोमेन टाका:",
      "linkPlaceholder": "उदा. https://fake-investment-fund.in किंवा telegram.me/vip_calls",
      "inspectUrlBtn": "डोमेन व एसएसएल तपासा",
      "messageLabel": "संशयास्पद संदेश किंवा व्हॉट्सअ‍ॅप मजकूर पेस्ट करा:",
      "messagePlaceholder": "वीज बिल कापण्याची धमकी, लॉटरी संदेश, वर्क फ्रॉम होम जॉब ऑफर...",
      "inspectMsgBtn": "एआय मजकूर तपासणी करा",
      "voiceTitle": "कॉल रेकॉर्डिंग किंवा ऑडिओ क्लिप अपलोड / रेकॉर्ड करा",
      "voiceDesc": "डीपफेक क्लोन व धमकीच्या आवाजाची स्पेक्ट्रम तपासणी.",
      "startRecord": "रेकॉर्डिंग सुरू करा",
      "stopRecord": "रेकॉर्डिंग थांबवा",
      "uploadAudio": "ऑडिओ फाइल निवडा",
      "analyzing": "एआय फॉरेन्सिक तपासणी सुरू आहे...",
      "analyzingSub": "सेबी, एनपीसीआय व सायबर गुन्हे डेटाबेसशी पडताळणी करत आहे...",
      "fullAuditBtn": "संपूर्ण फॉरेन्सिक अहवाल तयार करा"
    },
    "footer": {
      "advisoryTitle": "अधिकृत सूचना:",
      "advisoryText": "संज्ञान शील्ड गुंतवणुकीचा सल्ला देत नाही. आम्ही पैसे हस्तांतरित करण्यापूर्वी केवळ ओळख, नोंदणी आणि फसवणूक पॅटर्नची स्वतंत्र पडताळणी करतो.",
      "brandDesc": "भारतासाठी राष्ट्रीय नागरिक फिनटेक एआय पडताळणी शील्ड. यूपीआय घोटाळे, बनावट अ‍ॅप्स आणि सोशल इंजिनीअरिंगपासून सुरक्षितता.",
      "confidentialBadge": "१००% गोपनीय • भारतासाठी निर्मित • शून्य डेटा विक्री",
      "portalsHeading": "शासकीय व संस्थात्मक पोर्टल्स",
      "navHeading": "जलद नेव्हिगेशन",
      "helplineHeading": "आपत्कालीन मदत",
      "rights": "सर्व हक्क राखीव. नागरिक सायबर संरक्षण उपक्रम."
    }
  },
  "bn": {
    "slogan": "সংজ্ঞান শিল্ড • টাকা পাঠানোর আগে যাচাই করুন",
    "nav": {
      "home": "হোম",
      "verify": "যাচাই ওয়ার্কস্পেস",
      "history": "অডিট ইতিহাস",
      "learn": "সচেতনতা পাঠ",
      "report": "প্রতারণা অভিযোগ",
      "emergency": "জরুরি ১৯৩০",
      "verified": "যাচাইকৃত নাগরিক",
      "historyAction": "যাচাই ইতিহাস",
      "reportAction": "অভিযোগ ও এফআইআর",
      "alertsAction": "এসএমএস ও ইউপিআই সতর্কবার্তা",
      "signOut": "লগ আউট / পরিচয় বদলান"
    },
    "hero": {
      "badge": "এআই-চালিত ভারত সাইবার সুরক্ষা কবচ",
      "title": "টাকা পাঠানোর আগে মেসেজ, লিঙ্ক বা বিনিয়োগের পরামর্শ যাচাই করুন!",
      "subtitle": "নিরাপদ এবং স্বাবলম্বী ভারতের জন্য সার্বভৌম এআই যাচাইকরণ ব্যবস্থা",
      "desc": "হোয়াটসঅ্যাপ মেসেজ, টেলিগ্রাম ট্রেডিং গ্রুপ, সেবি নম্বর ও ইউপিআই হ্যান্ডেল তাৎক্ষণিক যাচাই করুন। সকল নাগরিকের জন্য সম্পূর্ণ বিনামূল্যে।",
      "startBtn": "যাচাই শুরু করুন",
      "learnBtn": "সচেতনতা পাঠ দেখুন",
      "stat1": "৩.২ লাখ+ জালিয়াতি প্রতিহত",
      "stat2": "₹৪২ কোটি টাকা সুরক্ষিত",
      "stat3": "নাগরিকদের জন্য ১০০% বিনামূল্যে"
    },
    "actions": {
      "card1Title": "স্ক্রিনশট আপলোড করুন",
      "card1Desc": "হোয়াটসঅ্যাপ চ্যাট, জাল রসিদ এবং টেলিগ্রাম মেসেজের তাৎক্ষণিক ওসিআর স্ক্যান।",
      "card1Tag": "দ্রুত ওসিআর",
      "card1Action": "নথি স্ক্যান করুন",
      "card2Title": "সন্দেহজনক লিঙ্ক পরীক্ষা",
      "card2Desc": "ভুয়া বিনিয়োগ পোর্টাল, ক্ষতিকারক এপিকে ডাউনলোড ও ফিশিং ডোমেন পরীক্ষা।",
      "card2Tag": "ডোমেন ও এসএসএল",
      "card2Action": "ইউআরএল পরীক্ষা করুন",
      "card3Title": "মেসেজ পরীক্ষা করুন",
      "card3Desc": "বিদ্যুৎ বিল কাটার ভুয়া হুমকি, লটারি ও চাকরি অফারের মেসেজ বিশ্লেষণ।",
      "card3Tag": "ভাষা বিশ্লেষণ",
      "card3Action": "মেসেজ পেস্ট করুন",
      "card4Title": "ডিপফেক ও ভয়েস পরীক্ষা",
      "card4Desc": "এআই-নির্মিত ভুয়া কণ্ঠস্বর এবং হুমকি অডিওর তাৎক্ষণিক ফোরেনসিক পরীক্ষা।",
      "card4Tag": "ভয়েস স্পেকট্রাম",
      "card4Action": "অডিও পরীক্ষা করুন"
    },
    "verifyBar": {
      "tag": "দ্রুত মাল্টি-মোডাল যাচাইকরণ বার",
      "title": "সন্দেহজনক অনুরোধ এখনই যাচাই করুন",
      "privacy": "জিরো সার্ভার স্টোরেজ • তাৎক্ষণিক ক্রিপ্টোগ্রাফিক হ্যাশ যাচাই",
      "placeholder": "ইউপিআই আইডি, লিঙ্ক, ফোন বা মেসেজ এখানে পেস্ট করুন...",
      "paste": "পেস্ট করুন",
      "verifyBtn": "যাচাই করুন",
      "samplePrompt": "নমুনা পরীক্ষা করুন:",
      "safeTitle": "যাচাইকৃত নিরাপদ প্রতিষ্ঠান (Verified Safe)",
      "safeDesc": "অফিসিয়াল সেবি/এনপিসিআই ডিরেক্টরিতে নিবন্ধিত। ব্যাংক গেটওয়ে সম্পূর্ণ নিরাপদ।",
      "dangerTitle": "উচ্চ সাইবার ঝুঁকি সংকেত (High Fraud Signal)",
      "dangerDesc": "সতর্কতা: এই তথ্য ১৯৩০ সাইবার হেল্পলাইনে পূর্বে দায়ের করা অভিযোগের সাথে মিলেছে। টাকা পাঠাবেন না!",
      "reportBtn": "অভিযোগ দায়ের করুন",
      "auditBtn": "সম্পূর্ণ ফরেনসিক রিপোর্ট"
    },
    "howItWorks": {
      "tag": "সুরক্ষা প্রক্রিয়া",
      "title": "সংজ্ঞান শিল্ড ৩টি ধাপে যেভাবে রক্ষা করে",
      "subtitle": "জটিল সাইবার জালিয়াতি কয়েক সেকেন্ডে চিহ্নিত করার আধুনিক প্রযুক্তি",
      "step1Title": "১. ইনপুট প্রদান করুন",
      "step1Desc": "সন্দেহজনক ইউপিআই, লিঙ্ক, স্ক্রিনশট বা মেসেজ জমা দিন।",
      "step2Title": "২. এআই যাচাইকরণ",
      "step2Desc": "সেবি, এনপিসিআই ও সাইবার অপরাধ ডাটাবেসের সাথে রিয়েল-টাইম ম্যাচ।",
      "step3Title": "৩. তাৎক্ষণিক সুরক্ষা রায়",
      "step3Desc": "সুরক্ষা স্কোর, ১৯৩০ ফ্রড ফ্রিজ গাইড এবং এফআইআর প্রমাণের বিবরণ পান।"
    },
    "threatRadar": {
      "tag": "লাইভ থ্রেট রাডার",
      "title": "সক্রিয় ভারত সাইবার জালিয়াতি সতর্কবার্তা",
      "subtitle": "ভারতীয় সাইবার ক্রাইম কোঅর্ডিনেশন সেন্টারের (I4C) সাথে সরাসরি যুক্ত",
      "alert1Title": "ভুয়া এসবিআই রিওয়ার্ড এপিকে",
      "alert1Desc": "মেসেজের মাধ্যমে এপিকে লিঙ্ক পাঠিয়ে ওটিপি ও পাসওয়ার্ড চুরির চেষ্টা।",
      "alert2Title": "টেলিগ্রাম পার্ট-টাইম জব স্ক্যাম",
      "alert2Desc": "ভিডিও লাইক করার নামে প্রতিদিন ৩,৫০০ টাকা আয়ের প্রলোভন।",
      "alert3Title": "ডিজিটাল অ্যারেস্ট সিবিআই জালিয়াতি",
      "alert3Desc": "পার্সেলে মাদক পাওয়ার ভয় দেখিয়ে ভিডিও কলে টাকা আদায়।"
    },
    "helplineBanner": {
      "goldenHour": "গোল্ডেন আওয়ার: ২ ঘণ্টার মধ্যে অভিযোগ দায়ের করুন",
      "title": "অনলাইন প্রতারণায় টাকা হারিয়েছেন? অবিলম্বে ১৯৩০ ডায়াল করুন",
      "desc": "জাতীয় সাইবার পোর্টাল অপরাধীর ব্যাংক অ্যাকাউন্ট তাৎক্ষণিক ফ্রিজ করতে পারে।",
      "callBtn": "১৯৩০ নম্বরে কল করুন",
      "portalBtn": "অফিসিয়াল পোর্টাল (MHA)",
      "dossierBtn": "এফআইআর ডজিয়ার তৈরি করুন"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "হোম",
      "breadcrumbWorkspace": "নাগরিক যাচাই ওয়ার্কস্পেস",
      "engineVersion": "এআই শিল্ড ইঞ্জিন v4.2",
      "registryConnected": "সেবি ও এনপিসিআই ডিরেক্টরি: সংযুক্ত",
      "ramProcessed": "১০০% র‍্যাম নিরাপদ প্রক্রিয়াকরণ",
      "title": "টাকা পাঠানোর আগে যাচাই করুন",
      "subtitle": "যেকোনো বিনিয়োগ পরামর্শ, টেলিগ্রাম টিপ বা ইউপিআই পেমেন্টের সত্যতা পরীক্ষা করুন।",
      "tabScreenshot": "স্ক্রিনশট",
      "tabLink": "লিঙ্ক / ডোমেন",
      "tabMessage": "মেসেজ",
      "tabVoice": "ভয়েস / অডিও",
      "dropzoneTitle": "স্ক্রিনশট এখানে টেনে এনে ড্রপ করুন, অথবা",
      "browseFiles": "ফাইল ব্রাউজ করুন",
      "dropzoneHint": "(জেপিজি, পিএনজি, হোয়াটসঅ্যাপ চ্যাট, টেলিগ্রাম স্ক্রিনশট ১০ এমবি পর্যন্ত)",
      "ocrTag": "ওসিআর টেক্সট নিষ্কাশন",
      "qrTag": "ইউপিআই কিউআর কোড পার্সিং",
      "sealTag": "জাল সিল শনাক্তকরণ",
      "sampleHeading": "অথবা পূর্বনির্ধারিত ভারতীয় প্রতারণা নমুনা দিয়ে দ্রুত পরীক্ষা করুন:",
      "clickToTest": "পরীক্ষা করতে যেকোনো একটিতে ক্লিক করুন",
      "linkLabel": "পরীক্ষা করার জন্য ওয়েবসাইট লিঙ্ক বা ডোমেন লিখুন:",
      "linkPlaceholder": "যেমন: https://fake-investment-fund.in অথবা telegram.me/vip_calls",
      "inspectUrlBtn": "ডোমেন ও এসএসএল পরীক্ষা করুন",
      "messageLabel": "সন্দেহজনক মেসেজ বা হোয়াটসঅ্যাপ টেক্সট পেস্ট করুন:",
      "messagePlaceholder": "বিদ্যুৎ বিলের হুমকি, লটারি জেতার বার্তা, ঘরে বসে কাজের প্রলোভন...",
      "inspectMsgBtn": "এআই টেক্সট ফরেনসিক চালান",
      "voiceTitle": "কল রেকর্ডিং বা অডিও আপলোড / রেকর্ড করুন",
      "voiceDesc": "ডিপফেক ভয়েস ক্লোন ও হুমকি কণ্ঠস্বরের স্পেকট্রাম বিশ্লেষণ।",
      "startRecord": "রেকর্ডিং শুরু করুন",
      "stopRecord": "রেকর্ডিং বন্ধ করুন",
      "uploadAudio": "অডিও ফাইল আপলোড করুন",
      "analyzing": "এআই ফরেনসিক বিশ্লেষণ চলছে...",
      "analyzingSub": "সেবি, এনপিসিআই এবং সাইবার অপরাধ ডাটাবেস চেক করা হচ্ছে...",
      "fullAuditBtn": "সম্পূর্ণ ফরেনসিক রিপোর্ট তৈরি করুন"
    },
    "footer": {
      "advisoryTitle": "অফিসিয়াল সতর্কতা:",
      "advisoryText": "সংজ্ঞান শিল্ড বিনিয়োগ পরামর্শ দেয় না। আমরা টাকা স্থানান্তরের আগে কেবল পরিচয়, লাইসেন্স ও স্ক্যাম প্যাটার্ন স্বাধীনভাবে যাচাই করি।",
      "brandDesc": "ভারতের জন্য জাতীয় নাগরিক ফিনটেক এআই যাচাইকরণ শিল্ড। ইউপিআই স্ক্যাম, ভুয়া অ্যাপ ও সোশ্যাল ইঞ্জিনিয়ারিং থেকে রিয়েল-টাইম সুরক্ষা।",
      "confidentialBadge": "১০০% গোপনীয় • ভারতের জন্য তৈরি • জিরো ডেটা বিক্রি",
      "portalsHeading": "প্রাতিষ্ঠানিক পোর্টাল",
      "navHeading": "দ্রুত নেভিগেশন",
      "helplineHeading": "জরুরি সহায়তা",
      "rights": "সর্বস্বত্ব সংরক্ষিত। নাগরিক সাইবার সুরক্ষা উদ্যোগ।"
    }
  },
  "te": {
    "slogan": "సంజ్ఞాన్ షీల్డ్ • చెల్లించే ముందు ధృవీకరించండి",
    "nav": {
      "home": "హోమ్",
      "verify": "ధృవీకరణ వర్క్‌స్పేస్",
      "history": "ఆడిట్ చరిత్ర",
      "learn": "అవగాహన పాఠాలు",
      "report": "మోసం ఫిర్యాదు",
      "emergency": "అత్యవసర 1930",
      "verified": "ధృవీకరించబడిన పౌరుడు",
      "historyAction": "ధృవీకరణ చరిత్ర",
      "reportAction": "ఫిర్యాదులు & ఎఫ్ఐఆర్",
      "alertsAction": "ఎస్ఎంఎస్ & యూపీఐ హెచ్చరికలు",
      "signOut": "లాగ్ అవుట్ / ఖాతా మార్చండి"
    },
    "hero": {
      "badge": "ఏఐ ఆధారిత భారత్ సైబర్ రక్షణ కవచం",
      "title": "డబ్బు పంపే ముందు సందేశం, లింక్ లేదా పెట్టుబడి సలహాను ధృవీకరించండి!",
      "subtitle": "సురక్షితమైన మరియు సమర్థవంతమైన భారతదేశం కోసం స్వదేశీ ఏఐ ధృవీకరణ వ్యవస్థ",
      "desc": "వాట్సాప్ సందేశాలు, టెలిగ్రామ్ గ్రూపులు, సెబీ రిజిస్ట్రేషన్ మరియు యూపీఐ వివరాలను తక్షణమే తనిఖీ చేయండి. పౌరులందరికీ 100% ఉచితం.",
      "startBtn": "ధృవీకరణ ప్రారంభించండి",
      "learnBtn": "అవగాహన పాఠాలు చూడండి",
      "stat1": "3.2 లక్షలకు పైగా మోసాలు అడ్డుకోబడ్డాయి",
      "stat2": "₹42 కోట్ల పౌరుల సంపద రక్షణ",
      "stat3": "పౌరులకు 100% ఉచిత సేవ"
    },
    "actions": {
      "card1Title": "స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి",
      "card1Desc": "వాట్సాప్ చాట్, నకిలీ రసీదులు మరియు టెలిగ్రామ్ సందేశాల తక్షణ ఓసీఆర్ స్కానింగ్.",
      "card1Tag": "తక్షణ ఓసీఆర్",
      "card1Action": "పత్రం స్కాన్ చేయండి",
      "card2Title": "అనుమానాస్పద లింక్ తనిఖీ",
      "card2Desc": "నకిలీ పెట్టుబడి పోర్టల్స్, మోసపూరిత ఏపీకేలు మరియు ఫిషింగ్ డొమైన్ల విశ్లేషణ.",
      "card2Tag": "డొమైన్ & ఎస్ఎస్ఎల్",
      "card2Action": "యూఆర్ఎల్ తనిఖీ చేయండి",
      "card3Title": "సందేశాన్ని పరిశీలించండి",
      "card3Desc": "కరెంట్ బిల్లు కట్, లాటరీ బహుమతులు మరియు ఉద్యోగ మోసాల ఏఐ విశ్లేషణ.",
      "card3Tag": "భాషా విశ్లేషణ",
      "card3Action": "సందేశం పేస్ట్ చేయండి",
      "card4Title": "డీప్‌ఫేక్ & వాయిస్ తనిఖీ",
      "card4Desc": "కృత్రిమ మేధ ద్వారా సృష్టించిన నకిలీ వాయిస్ మరియు బెదిరింపు ఆడియోలను గుర్తించండి.",
      "card4Tag": "వాయిస్ స్పెక్ట్రమ్",
      "card4Action": "ఆడియో తనిఖీ చేయండి"
    },
    "verifyBar": {
      "tag": "వేగవంతమైన మల్టీ-మోడల్ ధృవీకరణ బార్",
      "title": "అనుమానాస్పద అభ్యర్థనను ఇప్పుడే తనిఖీ చేయండి",
      "privacy": "జీరో సర్వర్ నిల్వ • తక్షణ క్రిప్టోగ్రాఫిక్ హాష్ తనిఖీ",
      "placeholder": "యూపీఐ ఐడీ, లింక్, ఫోన్ లేదా సందేశాన్ని ఇక్కడ పేస్ట్ చేయండి...",
      "paste": "పేస్ట్ చేయండి",
      "verifyBtn": "ధృవీకరించండి",
      "samplePrompt": "నమూనాలను పరీక్షించండి:",
      "safeTitle": "ధృవీకరించబడిన సురక్షిత సంస్థ (Verified Safe)",
      "safeDesc": "అధికారిక సెబీ / ఎన్‌పీసీఐ డైరెక్టరీలో ధృవీకరించబడింది. బ్యాంక్ గేట్‌వే సురక్షితం.",
      "dangerTitle": "అధిక సైబర్ మోసం హెచ్చరిక (High Fraud Signal)",
      "dangerDesc": "హెచ్చరిక: ఈ సమాచారం 1930 సైబర్ హెల్ప్‌లైన్‌లో నమోదైన ఫిర్యాదులతో సరిపోలింది. డబ్బు చెల్లించవద్దు!",
      "reportBtn": "ఫిర్యాదు చేయండి",
      "auditBtn": "పూర్తి ఫోరెన్సిక్ రిపోర్ట్"
    },
    "howItWorks": {
      "tag": "రక్షణ విధానం",
      "title": "సంజ్ఞాన్ షీల్డ్ 3 దశల్లో ఎలా రక్షిస్తుంది",
      "subtitle": "క్లిష్టమైన సైబర్ మోసాలను సెకన్లలో గుర్తించే అత్యాధునిక ఏఐ సాంకేతికత",
      "step1Title": "1. సమాచారం ఇవ్వండి",
      "step1Desc": "అనుమానాస్పద యూపీఐ, లింక్, స్క్రీన్‌షాట్ లేదా ఆడియోను నమోదు చేయండి.",
      "step2Title": "2. ఏఐ తనిఖీ",
      "step2Desc": "సెబీ, ఎన్‌పీసీఐ మరియు సైబర్ క్రైమ్ డేటాబేస్‌లతో ప్రత్యక్ష ధృవీకరణ.",
      "step3Title": "3. రక్షణ తీర్పు",
      "step3Desc": "భద్రతా స్కోరు, 1930 ఖాతా స్తంభింపజేసే మార్గదర్శకాలు మరియు ఎఫ్ఐఆర్ సాక్ష్యాల నివేదిక."
    },
    "threatRadar": {
      "tag": "ప్రత్యక్ష ముప్పు రాడార్",
      "title": "భారతదేశంలో చురుకైన సైబర్ మోసాల అలర్ట్",
      "subtitle": "ఇండియన్ సైబర్ క్రైమ్ కోఆర్డినేషన్ సెంటర్ (I4C) భాగస్వామ్యంతో ప్రత్యక్ష సమాచారం",
      "alert1Title": "నకిలీ ఎస్‌బీఐ రివార్డ్ ఏపీకే",
      "alert1Desc": "మెసేజ్ ద్వారా నకిలీ యాప్ పంపి బ్యాంక్ ఓటీపీ దొంగిలించే ప్రయత్నం.",
      "alert2Title": "టెలిగ్రామ్ పార్ట్‌టైమ్ జాబ్ మోసం",
      "alert2Desc": "వీడియోలు లైక్ చేస్తే రోజూ ₹3,500 వస్తుందని నమ్మించి డబ్బులు వసూలు చేసే మోసం.",
      "alert3Title": "డిజిటల్ అరెస్ట్ సీబీఐ మోసం",
      "alert3Desc": "కొరియర్‌లో మత్తుపదార్థాలు దొరికాయని వీడియో కాల్ చేసి బెదిరించే మోసం."
    },
    "helplineBanner": {
      "goldenHour": "గోల్డెన్ అవర్: 2 గంటల్లోపు ఫిర్యాదు చేయండి",
      "title": "ఆన్‌లైన్ మోసంలో డబ్బు కోల్పోయారా? వెంటనే 1930కి కాల్ చేయండి",
      "desc": "జాతీయ సైబర్ పోర్టల్ మోసగాళ్ల బ్యాంక్ ఖాతాలను తక్షణమే స్తంభింపజేయగలదు.",
      "callBtn": "1930కి కాల్ చేయండి",
      "portalBtn": "అధికారిక పోర్టల్ (MHA)",
      "dossierBtn": "ఎఫ్ఐఆర్ నివేదిక సిద్ధం చేయండి"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "హోమ్",
      "breadcrumbWorkspace": "పౌర ధృవీకరణ వర్క్‌స్పేస్",
      "engineVersion": "ఏఐ షీల్డ్ ఇంజిన్ v4.2",
      "registryConnected": "సెబీ & ఎన్‌పీసీఐ రిజిస్ట్రీ: అనుసంధానించబడింది",
      "ramProcessed": "100% ర్యామ్ సురక్షిత ప్రాసెసింగ్",
      "title": "చెల్లించే ముందు ధృవీకరించండి",
      "subtitle": "పెట్టుబడి సలహా, టెలిగ్రామ్ చిట్కా లేదా యూపీఐ చెల్లింపు అభ్యర్థనను క్షుణ్ణంగా తనిఖీ చేయండి.",
      "tabScreenshot": "స్క్రీన్‌షాట్",
      "tabLink": "లింక్ / డొమైన్",
      "tabMessage": "సందేశం",
      "tabVoice": "వాయిస్ / ఆడియో",
      "dropzoneTitle": "స్క్రీన్‌షాట్‌ను ఇక్కడ డ్రాగ్ చేసి వేయండి, లేదా",
      "browseFiles": "ఫైళ్లను ఎంచుకోండి",
      "dropzoneHint": "(జేపీజీ, పీఎన్‌జీ, వాట్సాప్ చాట్, టెలిగ్రామ్ స్క్రీన్‌షాట్ 10 ఎంబీ వరకు)",
      "ocrTag": "ఓసీఆర్ టెక్స్ట్ గుర్తింపు",
      "qrTag": "యూపీఐ క్యూఆర్ కోడ్ పార్సింగ్",
      "sealTag": "నకిలీ ముద్ర గుర్తింపు",
      "sampleHeading": "లేదా ముందే లోడ్ చేసిన భారతీయ మోసాల నమూనాలతో పరీక్షించండి:",
      "clickToTest": "పరీక్షించడానికి దేనినైనా ఎంచుకోండి",
      "linkLabel": "తనిఖీ చేయడానికి వెబ్‌సైట్ లింక్ లేదా డొమైన్ నమోదు చేయండి:",
      "linkPlaceholder": "ఉదా. https://fake-investment-fund.in లేదా telegram.me/vip_calls",
      "inspectUrlBtn": "డొమైన్ & ఎస్ఎస్ఎల్ తనిఖీ చేయండి",
      "messageLabel": "అనుమానాస్పద సందేశం లేదా వాట్సాప్ వచనాన్ని పేస్ట్ చేయండి:",
      "messagePlaceholder": "విద్యుత్ బిల్లు హెచ్చరిక, లాటరీ గెలుపు మెసేజ్, ఇంటి నుండి పని చేసే ఉద్యోగ ఆఫర్...",
      "inspectMsgBtn": "ఏఐ వచన విశ్లేషణ ప్రారంభించండి",
      "voiceTitle": "కాల్ రికార్డింగ్ లేదా ఆడియో క్లిప్ అప్‌లోడ్ / రికార్డ్ చేయండి",
      "voiceDesc": "డీప్‌ఫేక్ వాయిస్ క్లోన్ మరియు బెదిరింపు ఆడియోల స్పెక్ట్రమ్ విశ్లేషణ.",
      "startRecord": "రికార్డింగ్ ప్రారంభించండి",
      "stopRecord": "రికార్డింగ్ ఆపండి",
      "uploadAudio": "ఆడియో ఫైల్ అప్‌లోడ్ చేయండి",
      "analyzing": "ఏఐ ఫోరెన్సిక్ విశ్లేషణ జరుగుతోంది...",
      "analyzingSub": "సెబీ, ఎన్‌పీసీఐ మరియు సైబర్ క్రైమ్ డేటాబేస్ తనిఖీ చేస్తోంది...",
      "fullAuditBtn": "పూర్తి ఫోరెన్సిక్ రిపోర్ట్ రూపొందించండి"
    },
    "footer": {
      "advisoryTitle": "అధికారిక సలహా:",
      "advisoryText": "సంజ్ఞాన్ షీల్డ్ పెట్టుబడి సలహాలను ఇవ్వదు. మేము డబ్బు బదిలీ చేయడానికి ముందు గుర్తింపు, అధికారిక నమోదు మరియు మోసాల నమూనాలను మాత్రమే స్వతంత్రంగా తనిఖీ చేస్తాము.",
      "brandDesc": "భారతదేశం కోసం జాతీయ పౌర ఫిన్‌టెక్ ఏఐ ధృవీకరణ రక్షణ కవచం. యూపీఐ మోసాలు, నకిలీ యాప్‌ల నుండి రక్షణ.",
      "confidentialBadge": "100% గోప్యత • భారత్ కోసం నిర్మితం • జీరో డేటా అమ్మకం",
      "portalsHeading": "సంస్థాగత పోర్టల్స్",
      "navHeading": "త్వరిత నావిగేషన్",
      "helplineHeading": "అత్యవసర సహాయం",
      "rights": "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి. పౌర సైబర్ రక్షణ కార్యక్రమం."
    }
  },
  "ta": {
    "slogan": "சங்க்யான் ஷீல்ட் • பணம் செலுத்தும் முன் சரிபார்க்கவும்",
    "nav": {
      "home": "முகப்பு",
      "verify": "சரிபார்ப்பு தளம்",
      "history": "தணிக்கை வரலாறு",
      "learn": "விழிப்புணர்வு பாடங்கள்",
      "report": "மோசடி புகார்",
      "emergency": "அவசரம் 1930",
      "verified": "சரிபார்க்கப்பட்ட குடிமகன்",
      "historyAction": "சரிபார்ப்பு வரலாறு",
      "reportAction": "புகார்கள் & எஃப்ஐஆர்",
      "alertsAction": "எஸ்எம்எஸ் & யூபிஐ எச்சரிக்கைகள்",
      "signOut": "வெளியேறு / கணக்கு மாற்று"
    },
    "hero": {
      "badge": "ஏஐ இயங்கும் பாரத சைபர் பாதுகாப்பு கவசம்",
      "title": "பணம் செலுத்தும் முன் தகவல், இணைப்பு அல்லது முதலீட்டு ஆலோசனையை சரிபார்க்கவும்!",
      "subtitle": "பாதுகாப்பான மற்றும் வலுவான இந்தியாவிற்கான ஏஐ சரிபார்ப்பு அமைப்பு",
      "desc": "வாட்ஸ்அப் தகவல்கள், டெலிகிராம் குழுக்கள், செபி பதிவு மற்றும் யூபிஐ விவரங்களை உடனடியாக சரிபார்க்கவும். குடிமக்களுக்கு 100% இலவசம்.",
      "startBtn": "சரிபார்ப்பை தொடங்குங்கள்",
      "learnBtn": "பாடங்களை பார்க்கவும்",
      "stat1": "3.2 லட்சத்திற்கும் அதிகமான மோசடிகள் தடுப்பு",
      "stat2": "₹42 கோடி குடிமக்கள் பணம் பாதுகாப்பு",
      "stat3": "குடிமக்களுக்கு 100% இலவச சேவை"
    },
    "actions": {
      "card1Title": "ஸ்கிரீன்ஷாட் பதிவேற்றவும்",
      "card1Desc": "வாட்ஸ்அப் சாட், போலி ரசீதுகள் மற்றும் டெலிகிராம் தகவல்களை உடனடி ஓசிஆர் ஸ்கேன் செய்தல்.",
      "card1Tag": "உடனடி ஓசிஆர்",
      "card1Action": "ஆவணத்தை ஸ்கேன் செய்",
      "card2Title": "இணைப்பை சரிபார்க்கவும்",
      "card2Desc": "போலி முதலீட்டு தளங்கள், தீங்கு விளைவிக்கும் செயலிகள் மற்றும் ஃபிஷிங் தளங்களின் ஆய்வு.",
      "card2Tag": "டொமைன் & எஸ்எஸ்எல்",
      "card2Action": "தளத்தை சரிபார்க்கவும்",
      "card3Title": "செய்தியை சரிபார்க்கவும்",
      "card3Desc": "மின்சார கட்டண மிரட்டல், லாட்டரி மற்றும் போலி வேலைவாய்ப்பு செய்திகளை பகுப்பாய்வு செய்தல்.",
      "card3Tag": "மொழி பகுப்பாய்வு",
      "card3Action": "செய்தியை ஒட்டவும்",
      "card4Title": "டீப்ஃபேக் & குரல் ஆய்வு",
      "card4Desc": "செயற்கை நுண்ணறிவால் உருவாக்கப்பட்ட போலி குரல் மற்றும் மிரட்டல் ஆடியோக்களை கண்டறிதல்.",
      "card4Tag": "குரல் ஸ்பெக்ட்ரம்",
      "card4Action": "ஆடியோவை ஆய்வு செய்"
    },
    "verifyBar": {
      "tag": "விரைவான பல-முறை சரிபார்ப்பு பட்டி",
      "title": "சந்தேகத்திற்கிடமான கோரிக்கையை உடனே சரிபார்க்கவும்",
      "privacy": "சர்வரில் சேமிக்கப்படாது • உடனடி கிரிப்டோகிராஃபிக் ஹாஷ் சரிபார்ப்பு",
      "placeholder": "யூபிஐ ஐடி, இணைப்பு, தொலைபேசி அல்லது செய்தியை இங்கே ஒட்டவும்...",
      "paste": "ஒட்டு",
      "verifyBtn": "சரிபார்",
      "samplePrompt": "மாதிரிகளை சோதிக்கவும்:",
      "safeTitle": "சரிபார்க்கப்பட்ட பாதுகாப்பான நிறுவனம் (Verified Safe)",
      "safeDesc": "அதிகாரப்பூர்வ செபி / என்பிசிஐ தரவுத்தளத்தில் பதிவு செய்யப்பட்டுள்ளது. வங்கி நுழைவு பாதுகாப்பானது.",
      "dangerTitle": "அதிக சைபர் மோசடி எச்சரிக்கை (High Fraud Signal)",
      "dangerDesc": "எச்சரிக்கை: இந்த தகவல் 1930 சைபர் உதவி மையத்தில் ஏற்கனவே பதிவு செய்யப்பட்ட புகார்களுடன் பொருந்துகிறது. பணம் அனுப்ப வேண்டாம்!",
      "reportBtn": "புகார் அளிக்கவும்",
      "auditBtn": "முழுமையான தடயவியல் அறிக்கை"
    },
    "howItWorks": {
      "tag": "பாதுகாப்பு வழிமுறை",
      "title": "சங்க்யான் ஷீல்ட் 3 படிகளில் எவ்வாறு பாதுகாக்கிறது",
      "subtitle": "சிக்கலான சைபர் மோசடிகளை சில நொடிகளில் கண்டறியும் நவீன தொழில்நுட்பம்",
      "step1Title": "1. தகவலை உள்ளிடவும்",
      "step1Desc": "சந்தேகத்திற்கிடமான யூபிஐ, இணைப்பு, ஸ்கிரீன்ஷாட் அல்லது ஆடியோவை உள்ளிடவும்.",
      "step2Title": "2. ஏஐ சரிபார்ப்பு",
      "step2Desc": "செபி, என்பிசிஐ மற்றும் சைபர் குற்ற தரவுத்தளங்களுடன் நேரடி ஒப்பீடு.",
      "step3Title": "3. உடனடி பாதுகாப்பு தீர்ப்பு",
      "step3Desc": "பாதுகாப்பு மதிப்பீடு, 1930 வங்கி கணக்கு முடக்கும் வழிகாட்டி மற்றும் எஃப்ஐஆர் அறிக்கை பெறவும்."
    },
    "threatRadar": {
      "tag": "நேரடி அச்சுறுத்தல் ரேடார்",
      "title": "இந்தியாவில் நடப்பு சைபர் மோசடி எச்சரிக்கைகள்",
      "subtitle": "இந்திய சைபர் குற்ற ஒருங்கிணைப்பு மையம் (I4C) உடன் இணைக்கப்பட்டது",
      "alert1Title": "போலி எஸ்பிஐ ரிவார்ட் ஏபிகே",
      "alert1Desc": "எஸ்எம்எஸ் வழியாக போலி செயலியை அனுப்பி வங்கி ஓடிபியை திருடும் முயற்சி.",
      "alert2Title": "டெலிகிராம் பகுதிநேர வேலை மோசடி",
      "alert2Desc": "வீடியோக்களை லைக் செய்தால் தினமும் ₹3,500 தருவதாக கூறி பணத்தை பறிக்கும் மோசடி.",
      "alert3Title": "டிஜிட்டல் கைது சிபிஐ மோசடி",
      "alert3Desc": "பார்சலில் போதைப்பொருள் இருப்பதாக கூறி வீடியோ அழைப்பில் மிரட்டி பணம் பறிக்கும் மோசடி."
    },
    "helplineBanner": {
      "goldenHour": "கோல்டன் ஹவர்: 2 மணி நேரத்திற்குள் புகார் அளிக்கவும்",
      "title": "ஆன்லைன் மோசடியில் பணம் இழந்தீர்களா? உடனடியாக 1930 ஐ அழைக்கவும்",
      "desc": "தேசிய சைபர் போர்ட்டல் குற்றவாளியின் வங்கி கணக்கை உடனடியாக முடக்க முடியும்.",
      "callBtn": "1930 ஐ அழைக்கவும்",
      "portalBtn": "அதிகாரப்பூர்வ போர்டல் (MHA)",
      "dossierBtn": "எஃப்ஐஆர் ஆவணத்தை உருவாக்கவும்"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "முகப்பு",
      "breadcrumbWorkspace": "குடிமக்கள் சரிபார்ப்பு தளம்",
      "engineVersion": "ஏஐ ஷீல்ட் எஞ்சின் v4.2",
      "registryConnected": "செபி & என்பிசிஐ தரவுத்தளம்: இணைக்கப்பட்டது",
      "ramProcessed": "100% ரேம் பாதுகாப்பான செயலாக்கம்",
      "title": "பணம் செலுத்தும் முன் சரிபார்க்கவும்",
      "subtitle": "முதலீட்டு ஆலோசனை, டெலிகிராம் தகவல் அல்லது யூபிஐ பரிவர்த்தனையை உடனே சரிபார்க்கவும்.",
      "tabScreenshot": "ஸ்கிரீன்ஷாட்",
      "tabLink": "இணைப்பு / டொமைன்",
      "tabMessage": "செய்தி",
      "tabVoice": "குரல் / ஆடியோ",
      "dropzoneTitle": "ஸ்கிரீன்ஷாட்டை இங்கே இழுத்து விடவும், அல்லது",
      "browseFiles": "கோப்புகளைத் தேர்ந்தெடுக்கவும்",
      "dropzoneHint": "(ஜேபிஜி, பிஎன்ஜி, வாட்ஸ்அப் சாட், டெலிகிராம் ஸ்கிரீன்ஷாட் 10 எம்பி வரை)",
      "ocrTag": "ஓசிஆர் உரை பிரித்தெடுத்தல்",
      "qrTag": "யூபிஐ க்யூஆர் குறியீடு பகுப்பாய்வு",
      "sealTag": "போலி முத்திரை கண்டறிதல்",
      "sampleHeading": "அல்லது ஏற்கனவே உள்ள இந்திய மோசடி மாதிரிகளை சோதிக்கவும்:",
      "clickToTest": "சோதிக்க ஏதேனும் ஒன்றை கிளிக் செய்யவும்",
      "linkLabel": "சரிபார்க்க வேண்டிய இணையதள இணைப்பு அல்லது டொமைனை உள்ளிடவும்:",
      "linkPlaceholder": "எ.கா. https://fake-investment-fund.in அல்லது telegram.me/vip_calls",
      "inspectUrlBtn": "டொமைன் & எஸ்எஸ்எல் சரிபார்",
      "messageLabel": "சந்தேகத்திற்கிடமான செய்தி அல்லது வாட்ஸ்அப் உரையை ஒட்டவும்:",
      "messagePlaceholder": "மின்சார கட்டண அச்சுறுத்தல், லாட்டரி வெற்றி செய்தி, வீட்டிலிருந்து வேலை வாய்ப்பு...",
      "inspectMsgBtn": "ஏஐ உரை ஆய்வை இயக்கு",
      "voiceTitle": "அழைப்பு பதிவு அல்லது ஆடியோவை பதிவேற்றவும் / பதிவு செய்யவும்",
      "voiceDesc": "டீப்ஃபேக் போலி குரல்கள் மற்றும் மிரட்டல் ஆடியோக்களை ஆய்வு செய்யவும்.",
      "startRecord": "பதிவைத் தொடங்கவும்",
      "stopRecord": "பதிவை நிறுத்தவும்",
      "uploadAudio": "ஆடியோ கோப்பை பதிவேற்றவும்",
      "analyzing": "ஏஐ தடயவியல் பகுப்பாய்வு நடக்கிறது...",
      "analyzingSub": "செபி, என்பிசிஐ மற்றும் சைபர் குற்ற தரவுத்தளங்கள் சரிபார்க்கப்படுகின்றன...",
      "fullAuditBtn": "முழுமையான தடயவியல் அறிக்கையை உருவாக்கவும்"
    },
    "footer": {
      "advisoryTitle": "அதிகாரப்பூர்வ ஆலோசனை:",
      "advisoryText": "சங்க்யான் ஷீல்ட் முதலீட்டு ஆலோசனைகளை வழங்காது. பணம் அனுப்புவதற்கு முன் அடையாளம், உரிமம் மற்றும் மோசடி வடிவங்களை மட்டுமே நாங்கள் சுயாதீனமாக சரிபார்க்கிறோம்.",
      "brandDesc": "இந்தியாவிற்கான தேசிய குடிமக்கள் ஃபின்டெக் ஏஐ சரிபார்ப்பு கவசம். யூபிஐ மோசடிகள் மற்றும் போலி செயலிகளிலிருந்து பாதுகாப்பு.",
      "confidentialBadge": "100% ரகசியமானது • பாரதத்திற்காக உருவாக்கப்பட்டது • தரவு விற்பனை இல்லை",
      "portalsHeading": "அரசு மற்றும் நிறுவன போர்ட்டல்கள்",
      "navHeading": "விரைவு வழிசெலுத்தல்",
      "helplineHeading": "அவசர உதவி",
      "rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. குடிமக்கள் சைபர் பாதுகாப்பு முயற்சி."
    }
  },
  "gu": {
    "slogan": "સંજ્ઞાન શીલ્ડ • ચૂકવણી કરતા પહેલા ખાતરી કરો",
    "nav": {
      "home": "હોમ",
      "verify": "ચકાસણી વર્કસ્પેસ",
      "history": "ઓડિટ ઇતિહાસ",
      "learn": "જાગૃતિ પાઠ",
      "report": "છેતરપિંડી ફરિયાદ",
      "emergency": "ઇમરજન્સી 1930",
      "verified": "પ્રમાણિત નાગરિક",
      "historyAction": "ચકાસણી ઇતિહાસ",
      "reportAction": "નોંધાયેલી ફરિયાદો અને એફઆઈઆર",
      "alertsAction": "એસએમએસ અને યુપીઆઈ ચેતવણી",
      "signOut": "લૉગ આઉટ / એકાઉન્ટ બદલો"
    },
    "hero": {
      "badge": "એઆઈ-સંચાલિત ભારત સાયબર સુરક્ષા કવચ",
      "title": "પૈસા મોકલતા પહેલા સંદેશ, લિંક અથવા રોકાણ સલાહની ચકાસણી કરો!",
      "subtitle": "સુરક્ષિત અને સમર્થ ભારત માટે સ્વદેશી એઆઈ ચકાસણી પ્રણાલી",
      "desc": "વ્હોટ્સએપ ફોરવર્ડ, ટેલિગ્રામ ટ્રેડિંગ ગ્રુપ્સ, સેબી નોંધણી અને યુપીઆઈ વિગતો તરત જ તપાસો. તમામ નાગરિકો માટે ૧૦૦% મફત.",
      "startBtn": "ચકાસણી શરૂ કરો",
      "learnBtn": "જાગૃતિ પાઠ જુઓ",
      "stat1": "૩.૨ લાખથી વધુ છેતરપિંડી અટકાવાઈ",
      "stat2": "₹૪૨ કરોડનું નાગરિક ભંડોળ સુરક્ષિત",
      "stat3": "નાગરિકો માટે ૧૦૦% મફત સેવા"
    },
    "actions": {
      "card1Title": "સ્ક્રીનશોટ અપલોડ કરો",
      "card1Desc": "વ્હોટ્સએપ ચેટ, બનાવટી રસીદો અને ટેલિગ્રામ મેસેજનું ઝડપી ઓસીઆર સ્કેનિંગ.",
      "card1Tag": "ઝડપી ઓસીઆર",
      "card1Action": "દસ્તાવેજ સ્કેન કરો",
      "card2Title": "શંકાસ્પદ લિંક તપાસો",
      "card2Desc": "નકલી રોકાણ પોર્ટલ, જોખમી એપીકે અને ફિશિંગ ડોમેનની તાત્કાલિક તપાસ.",
      "card2Tag": "ડોમેન અને એસએસએલ",
      "card2Action": "યુઆરએલ તપાસો",
      "card3Title": "સંદેશ તપાસો",
      "card3Desc": "વીજળી બિલ કાપવાની ધમકી, લૉટરી અને નકલી નોકરીના મેસેજનું એઆઈ વિશ્લેષણ.",
      "card3Tag": "ભાષા વિશ્લેષણ",
      "card3Action": "મેસેજ પેસ્ટ કરો",
      "card4Title": "ડીપફેક અને વૉઇસ તપાસ",
      "card4Desc": "કૃત્રિમ બુદ્ધિ દ્વારા બનાવેલ નકલી અવાજ અને ધમકીભર્યા કૉલ્સ ઓળખો.",
      "card4Tag": "વૉઇસ સ્પેક્ટ્રમ",
      "card4Action": "ઑડિયો તપાસો"
    },
    "verifyBar": {
      "tag": "ઝડપી મલ્ટી-મોડલ વેરિફિકેશન બાર",
      "title": "શંકાસ્પદ વિનંતીની તરત જ ચકાસણી કરો",
      "privacy": "ઝીરો સર્વર સ્ટોરેજ • ત્વરિત ક્રિપ્ટોગ્રાફિક હેશ ચકાસણી",
      "placeholder": "યુપીઆઈ આઈડી, લિંક, ફોન અથવા સંદેશ અહીં પેસ્ટ કરો...",
      "paste": "પેસ્ટ કરો",
      "verifyBtn": "ચકાસણી કરો",
      "samplePrompt": "નમૂનાઓનું પરીક્ષણ કરો:",
      "safeTitle": "ચકાસાયેલ સુરક્ષિત સંસ્થા (Verified Safe)",
      "safeDesc": "સત્તાવાર સેબી / એનપીસીઆઈ ડિરેક્ટરીમાં નોંધાયેલ છે. બેંક પેમેન્ટ ગેટવે સુરક્ષિત છે.",
      "dangerTitle": "ઉચ્ચ સાયબર જોખમ ચેતવણી (High Fraud Signal)",
      "dangerDesc": "ચેતવણી: આ માહિતી ૧૯૩૦ સાયબર હેલ્પલાઇન પર અગાઉ નોંધાયેલી ફરિયાદો સાથે મેળ ખાય છે. પૈસા મોકલશો નહીં!",
      "reportBtn": "ફરિયાદ નોંધાવો",
      "auditBtn": "વિગતવાર ફોરેન્સિક રિપોર્ટ"
    },
    "howItWorks": {
      "tag": "સુરક્ષા પ્રક્રિયા",
      "title": "સંજ્ઞાન શીલ્ડ ૩ તબક્કામાં કેવી રીતે રક્ષણ કરે છે",
      "subtitle": "જટિલ સાયબર છેતરપિંડી સેકન્ડોમાં ઓળખતી અત્યાધુનિક સ્વદેશી તકનીક",
      "step1Title": "૧. માહિતી આપો",
      "step1Desc": "શંકાસ્પદ યુપીઆઈ, લિંક, સ્ક્રીનશોટ અથવા ઓડિયો અહીં દાખલ કરો.",
      "step2Title": "૨. એઆઈ ચકાસણી",
      "step2Desc": "સેબી, એનપીસીઆઈ અને સાયબર ક્રાઈમ ડેટાબેઝ સાથે ત્વરિત મેળ.",
      "step3Title": "૩. ત્વરિત સુરક્ષા નિર્ણય",
      "step3Desc": "સુરક્ષા સ્કોર, ૧૯૩૦ ફ્રોડ ફ્રીઝ માર્ગદર્શિકા અને એફઆઈઆર પુરાવા અહેવાલ મેળવો."
    },
    "threatRadar": {
      "tag": "લાઇવ થ્રેટ રડાર",
      "title": "સક્રિય ભારત સાયબર છેતરપિંડી એલર્ટ",
      "subtitle": "ઇન્ડિયન સાયબર ક્રાઇમ કોઓર્ડિનેશન સેન્ટર (I4C) ના સહયોગથી લાઇવ અપડેટ",
      "alert1Title": "નકલી એસબીઆઈ રિવોર્ડ એપીકે",
      "alert1Desc": "મેસેજ દ્વારા નકલી એપ મોકલીને બેંક ઓટીપી ચોરવાનો પ્રયાસ.",
      "alert2Title": "ટેલિગ્રામ પાર્ટ-ટાઇમ જોબ સ્કેમ",
      "alert2Desc": "વિડિયો લાઈક કરવા પર દરરોજ ₹૩,૫૦૦ આપવાનું વચન આપીને પૈસા પડાવતી ગેંગ.",
      "alert3Title": "ડિજિટલ એરેસ્ટ સીબીઆઈ સ્કેમ",
      "alert3Desc": "પાર્સલમાં નશીલા પદાર્થો હોવાનો ડર બતાવીને વિડિયો કોલ પર પૈસા પડાવવા."
    },
    "helplineBanner": {
      "goldenHour": "ગોલ્ડન અવર: ૨ કલાકની અંદર ફરિયાદ નોંધાવો",
      "title": "ઓનલાઈન છેતરપિંડીમાં પૈસા ગુમાવ્યા? તરત જ ૧૯૩૦ પર કૉલ કરો",
      "desc": "નેશનલ સાયબર પોર્ટલ ગુનેગારના બેંક ખાતાને તાત્કાલિક ફ્રીઝ કરી શકે છે.",
      "callBtn": "૧૯૩૦ પર કૉલ કરો",
      "portalBtn": "સત્તાવાર પોર્ટલ (MHA)",
      "dossierBtn": "એફઆઈઆર દસ્તાવેજ બનાવો"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "હોમ",
      "breadcrumbWorkspace": "નાગરિક ચકાસણી વર્કસ્પેસ",
      "engineVersion": "એઆઈ શીલ્ડ એન્જિન v4.2",
      "registryConnected": "સેબી અને એનપીસીઆઈ રજિસ્ટ્રી: જોડાયેલ છે",
      "ramProcessed": "૧૦૦% રેમ સુરક્ષિત પ્રક્રિયા",
      "title": "ચૂકવણી કરતા પહેલા ખાતરી કરો",
      "subtitle": "કોઈપણ રોકાણ સલાહ, ટેલિગ્રામ ટીપ અથવા યુપીઆઈ ચૂકવણી વિનંતીની સત્યતા તપાસો.",
      "tabScreenshot": "સ્ક્રીનશોટ",
      "tabLink": "લિંક / ડોમેન",
      "tabMessage": "સંદેશ",
      "tabVoice": "વૉઇસ / ઑડિયો",
      "dropzoneTitle": "સ્ક્રીનશોટ અહીં ડ્રેગ કરીને મૂકો, અથવા",
      "browseFiles": "ફાઇલો પસંદ કરો",
      "dropzoneHint": "(જેપીજી, પીએનજી, વ્હોટ્સએપ ચેટ, ટેલિગ્રામ સ્ક્રીનશોટ ૧૦ એમબી સુધી)",
      "ocrTag": "ઓસીઆર લખાણ નિષ્કર્ષણ",
      "qrTag": "યુપીઆઈ ક્યુઆર કોડ પાર્સિંગ",
      "sealTag": "બનાવટી સીલ ઓળખ",
      "sampleHeading": "અથવા અગાઉથી લોડ કરેલા ભારતીય છેતરપિંડી નમૂનાઓ સાથે ઝડપી પરીક્ષણ કરો:",
      "clickToTest": "પરીક્ષણ માટે કોઈપણ પર ક્લિક કરો",
      "linkLabel": "ચકાસણી માટે વેબસાઇટ લિંક અથવા ડોમેન દાખલ કરો:",
      "linkPlaceholder": "દા.ત. https://fake-investment-fund.in અથવા telegram.me/vip_calls",
      "inspectUrlBtn": "ડોમેન અને એસએસએલ તપાસો",
      "messageLabel": "શંકાસ્પદ સંદેશ અથવા વ્હોટ્સએપ લખાણ પેસ્ટ કરો:",
      "messagePlaceholder": "વીજળી બિલની ચેતવણી, લૉટરી જીતવાનો મેસેજ, વર્ક ફ્રોમ હોમ ઓફર...",
      "inspectMsgBtn": "એઆઈ લખાણ વિશ્લેષણ ચલાવો",
      "voiceTitle": "કૉલ રેકોર્ડિંગ અથવા ઑડિયો ક્લિપ અપલોડ / રેકોર્ડ કરો",
      "voiceDesc": "ડીપફેક અવાજ અને ધમકીભર્યા કૉલ્સનું સ્પેક્ટ્રમ વિશ્લેષણ.",
      "startRecord": "રેકોર્ડિંગ શરૂ કરો",
      "stopRecord": "રેકોર્ડિંગ બંધ કરો",
      "uploadAudio": "ઑડિયો ફાઇલ અપલોડ કરો",
      "analyzing": "એઆઈ ફોરેન્સિક વિશ્લેષણ ચાલુ છે...",
      "analyzingSub": "સેબી, એનપીસીઆઈ અને સાયબર ક્રાઈમ ડેટાબેઝ તપાસી રહ્યાં છીએ...",
      "fullAuditBtn": "સંપૂર્ણ ફોરેન્સિક અહેવાલ તૈયાર કરો"
    },
    "footer": {
      "advisoryTitle": "સત્તાવાર સલાહ:",
      "advisoryText": "સંજ્ઞાન શીલ્ડ રોકાણ સલાહ આપતું નથી. અમે નાણાં ટ્રાન્સફર કરતા પહેલા ઓળખ, લાઇસન્સ અને છેતરપિંડી પેટર્નની સ્વતંત્ર ચકાસણી કરીએ છીએ.",
      "brandDesc": "ભારત માટે રાષ્ટ્રીય નાગરિક ફિનટેક એઆઈ ચકાસણી શીલ્ડ. યુપીઆઈ કૌભાંડો અને નકલી એપ્સ સામે વાસ્તવિક સમયની સુરક્ષા.",
      "confidentialBadge": "૧૦૦% ગોપનીય • ભારત માટે નિર્મિત • ઝીરો ડેટા વેચાણ",
      "portalsHeading": "સંસ્થાકીય પોર્ટલ",
      "navHeading": "ઝડપી નેવિગેશન",
      "helplineHeading": "ઇમરજન્સી સહાય",
      "rights": "તમામ હકો અનામત. નાગરિક સાયબર સુરક્ષા પહેલ."
    }
  },
  "kn": {
    "slogan": "ಸಂಜ್ಞಾನ್ ಶೀಲ್ಡ್ • ಹಣ ಪಾವತಿಸುವ ಮುನ್ನ ಪರಿಶೀಲಿಸಿ",
    "nav": {
      "home": "ಮುಖಪುಟ",
      "verify": "ಪರಿಶೀಲನಾ ವರ್ಕ್‌ಸ್ಪೇಸ್",
      "history": "ಆಡಿಟ್ ಇತಿಹಾಸ",
      "learn": "ಜಾಗೃತಿ ಪಾಠಗಳು",
      "report": "ವಂಚನೆ ದೂರು",
      "emergency": "ತುರ್ತು 1930",
      "verified": "ದೃಢೀಕೃತ ನಾಗರಿಕ",
      "historyAction": "ಪರಿಶೀಲನಾ ಇತಿಹಾಸ",
      "reportAction": "ದೂರುಗಳು ಮತ್ತು ಎಫ್‌ಐಆರ್",
      "alertsAction": "ಎಸ್‌ಎಂಎಸ್ ಮತ್ತು ಯುಪಿಐ ಎಚ್ಚರಿಕೆ",
      "signOut": "ಲಾಗ್ ಔಟ್ / ಗುರುತು ಬದಲಿಸಿ"
    },
    "hero": {
      "badge": "ಎಐ-ಚಾಲಿತ ಭಾರತ ಸೈಬರ್ ರಕ್ಷಣಾ ಕವಚ",
      "title": "ಹಣ ಪಾವತಿಸುವ ಮೊದಲು ಸಂದೇಶ, ಲಿಂಕ್ ಅಥವಾ ಹೂಡಿಕೆ ಸಲಹೆಯನ್ನು ಪರಿಶೀಲಿಸಿ!",
      "subtitle": "ಸುರಕ್ಷಿತ ಮತ್ತು ಸಮರ್ಥ ಭಾರತಕ್ಕಾಗಿ ಸ್ವದೇಶಿ ಎಐ ಪರಿಶೀಲನಾ ವ್ಯವಸ್ಥೆ",
      "desc": "ವಾಟ್ಸಾಪ್ ಸಂದೇಶಗಳು, ಟೆಲಿಗ್ರಾಂ ಗುಂಪುಗಳು, ಸೆಬಿ ನೋಂದಣಿ ಮತ್ತು ಯುಪಿಐ ವಿವರಗಳನ್ನು ತಕ್ಷಣ ಪರಿಶೀಲಿಸಿ. ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕರಿಗೂ 100% ಉಚಿತ.",
      "startBtn": "ಪರಿಶೀಲನೆ ಪ್ರಾರಂಭಿಸಿ",
      "learnBtn": "ಪಾಠಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
      "stat1": "3.2 ಲಕ್ಷಕ್ಕೂ ಹೆಚ್ಚು ವಂಚನೆ ತಡೆಗಟ್ಟಲಾಗಿದೆ",
      "stat2": "₹42 ಕೋಟಿ ನಾಗರಿಕರ ಹಣ ರಕ್ಷಣೆ",
      "stat3": "ನಾಗರಿಕರಿಗೆ 100% ಉಚಿತ ಸೇವೆ"
    },
    "actions": {
      "card1Title": "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
      "card1Desc": "ವಾಟ್ಸಾಪ್ ಚಾಟ್, ನಕಲಿ ರಶೀದಿಗಳು ಮತ್ತು ಟೆಲಿಗ್ರಾಂ ಸಂದೇಶಗಳ ತ್ವರಿತ ಒಸಿಆರ್ ಸ್ಕ್ಯಾನಿಂಗ್.",
      "card1Tag": "ತ್ವರಿತ ಒಸಿಆರ್",
      "card1Action": "ದಾಖಲೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
      "card2Title": "ಅನುಮಾನಾಸ್ಪದ ಲಿಂಕ್ ಪರಿಶೀಲನೆ",
      "card2Desc": "ನಕಲಿ ಹೂಡಿಕೆ ಪೋರ್ಟಲ್‌ಗಳು, ಅಪಾಯಕಾರಿ ಎಪಿಕೆ ಮತ್ತು ಫಿಶಿಂಗ್ ಡೊಮೇನ್‌ಗಳ ವಿಶ್ಲೇಷಣೆ.",
      "card2Tag": "ಡೊಮೇನ್ ಮತ್ತು ಎಸ್‌ಎಸ್‌ಎಲ್",
      "card2Action": "ಯುಆರ್‌ಎಲ್ ಪರಿಶೀಲಿಸಿ",
      "card3Title": "ಸಂದೇಶ ಪರಿಶೀಲಿಸಿ",
      "card3Desc": "ವಿದ್ಯುತ್ ಬಿಲ್ ಕಡಿತ, ಲಾಟರಿ ಗೆಲುವು ಮತ್ತು ನಕಲಿ ಉದ್ಯೋಗದ ಸಂದೇಶಗಳ ಎಐ ವಿಶ್ಲೇಷಣೆ.",
      "card3Tag": "ಭಾಷಾ ವಿಶ್ಲೇಷಣೆ",
      "card3Action": "ಸಂದೇಶ ಪೇಸ್ಟ್ ಮಾಡಿ",
      "card4Title": "ಡೀಪ್‌ಫೇಕ್ ಮತ್ತು ಧ್ವನಿ ಪರಿಶೀಲನೆ",
      "card4Desc": "ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ ಮೂಲಕ ರಚಿಸಲಾದ ನಕಲಿ ಧ್ವನಿ ಮತ್ತು ಬೆದರಿಕೆ ಕರೆಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಿ.",
      "card4Tag": "ಧ್ವನಿ ಸ್ಪೆಕ್ಟ್ರಮ್",
      "card4Action": "ಆಡಿಯೋ ಪರಿಶೀಲಿಸಿ"
    },
    "verifyBar": {
      "tag": "ವೇಗದ ಬಹು-ಮಾದರಿ ಪರಿಶೀಲನಾ ಬಾರ್",
      "title": "ಅನುಮಾನಾಸ್ಪದ ವಿನಂತಿಯನ್ನು ತಕ್ಷಣ ಪರಿಶೀಲಿಸಿ",
      "privacy": "ಶೂನ್ಯ ಸರ್ವರ್ ಸಂಗ್ರಹಣೆ • ತಕ್ಷಣದ ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಹ್ಯಾಶ್ ಪರಿಶೀಲನೆ",
      "placeholder": "ಯುಪಿಐ ಐಡಿ, ಲಿಂಕ್, ಫೋನ್ ಅಥವಾ ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ...",
      "paste": "ಪೇಸ್ಟ್ ಮಾಡಿ",
      "verifyBtn": "ಪರಿಶೀಲಿಸಿ",
      "samplePrompt": "ಮಾದರಿಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ:",
      "safeTitle": "ದೃಢೀಕೃತ ಸುರಕ್ಷಿತ ಸಂಸ್ಥೆ (Verified Safe)",
      "safeDesc": "ಅಧಿಕೃತ ಸೆಬಿ / ಎನ್‌ಪಿಸಿಐ ನಿರ್ದೇಶಿಕೆಯಲ್ಲಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ. ಬ್ಯಾಂಕ್ ಪಾವತಿ ಗೇಟ್‌ವೇ ಸುರಕ್ಷಿತವಾಗಿದೆ.",
      "dangerTitle": "ಹೆಚ್ಚಿನ ಸೈಬರ್ ವಂಚನೆ ಎಚ್ಚರಿಕೆ (High Fraud Signal)",
      "dangerDesc": "ಎಚ್ಚರಿಕೆ: ಈ ಮಾಹಿತಿಯು 1930 ಸೈಬರ್ ಸಹಾಯವಾಣಿಯಲ್ಲಿ ದಾಖಲಾದ ದೂರುಗಳೊಂದಿಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. ಹಣ ಪಾವತಿಸಬೇಡಿ!",
      "reportBtn": "ದೂರು ದಾಖಲಿಸಿ",
      "auditBtn": "ಸಂಪೂರ್ಣ ವಿಧಿವಿಜ್ಞಾನ ವರದಿ"
    },
    "howItWorks": {
      "tag": "ರಕ್ಷಣಾ ಪ್ರಕ್ರಿಯೆ",
      "title": "ಸಂಜ್ಞಾನ್ ಶೀಲ್ಡ್ 3 ಹಂತಗಳಲ್ಲಿ ಹೇಗೆ ರಕ್ಷಿಸುತ್ತದೆ",
      "subtitle": "ಸಂಕೀರ್ಣ ಸೈಬರ್ ವಂಚನೆಗಳನ್ನು ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಗುರುತಿಸುವ ಅತ್ಯಾಧುನಿಕ ತಂತ್ರಜ್ಞಾನ",
      "step1Title": "1. ಮಾಹಿತಿ ನಮೂದಿಸಿ",
      "step1Desc": "ಅನುಮಾನಾಸ್ಪದ ಯುಪಿಐ, ಲಿಂಕ್, ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಥವಾ ಆಡಿಯೋವನ್ನು ಇಲ್ಲಿ ನಮೂದಿಸಿ.",
      "step2Title": "2. ಎಐ ಪರಿಶೀಲನೆ",
      "step2Desc": "ಸೆಬಿ, ಎನ್‌ಪಿಸಿಐ ಮತ್ತು ಸೈಬರ್ ಅಪರಾಧ ದತ್ತಸಂಚಯಗಳೊಂದಿಗೆ ತಕ್ಷಣದ ಹೋಲಿಕೆ.",
      "step3Title": "3. ತಕ್ಷಣದ ರಕ್ಷಣಾ ತೀರ್ಪು",
      "step3Desc": "ಸುರಕ್ಷತಾ ಅಂಕ, 1930 ಬ್ಯಾಂಕ್ ಖಾತೆ ಸ್ಥಗಿತಗೊಳಿಸುವ ಮಾರ್ಗದರ್ಶಿ ಮತ್ತು ಎಫ್‌ಐಆರ್ ಪುರಾವೆ ವರದಿ ಪಡೆಯಿರಿ."
    },
    "threatRadar": {
      "tag": "ಲೈವ್ ಸೈಬರ್ ರೇಡಾರ್",
      "title": "ಸಕ್ರಿಯ ಭಾರತ ಸೈಬರ್ ವಂಚನೆ ಎಚ್ಚರಿಕೆಗಳು",
      "subtitle": "ಭಾರತೀಯ ಸೈಬರ್ ಅಪರಾಧ ಸಮನ್ವಯ ಕೇಂದ್ರದ (I4C) ಸಹಯೋಗದೊಂದಿಗೆ ನೇರ ಮಾಹಿತಿ",
      "alert1Title": "ನಕಲಿ ಎಸ್‌ಬಿಐ ರಿವಾರ್ಡ್ ಎಪಿಕೆ",
      "alert1Desc": "ಮೆಸೇಜ್ ಮೂಲಕ ನಕಲಿ ಆ್ಯಪ್ ಕಳುಹಿಸಿ ಬ್ಯಾಂಕ್ ಒಟಿಪಿ ಕದಿಯುವ ಯತ್ನ.",
      "alert2Title": "ಟೆಲಿಗ್ರಾಂ ಪಾರ್ಟ್-ಟೈಮ್ ಜಾಬ್ ವಂಚನೆ",
      "alert2Desc": "ವಿಡಿಯೋಗಳನ್ನು ಲೈಕ್ ಮಾಡಿದರೆ ಪ್ರತಿದಿನ ₹3,500 ನೀಡುವ ಆಮಿಷವೊಡ್ಡಿ ಹಣ ವಸೂಲಿ ಮಾಡುವ ಜಾಲ.",
      "alert3Title": "ಡಿಜಿಟಲ್ ಅರೆಸ್ಟ್ ಸಿಬಿಐ ವಂಚನೆ",
      "alert3Desc": "ಪಾರ್ಸೆಲ್‌ನಲ್ಲಿ ಮಾದಕವಸ್ತು ಇದೆ ಎಂದು ಹೆದರಿಸಿ ವಿಡಿಯೋ ಕರೆ ಮೂಲಕ ಹಣ ವಸೂಲಿ."
    },
    "helplineBanner": {
      "goldenHour": "ಗೋಲ್ಡನ್ ಅವರ್: 2 ಗಂಟೆಗಳ ಒಳಗೆ ದೂರು ದಾಖಲಿಸಿ",
      "title": "ಆನ್‌ಲೈನ್ ವಂಚನೆಯಲ್ಲಿ ಹಣ ಕಳೆದುಕೊಂಡಿದ್ದೀರಾ? ತಕ್ಷಣವೇ 1930 ಗೆ ಕರೆ ಮಾಡಿ",
      "desc": "ರಾಷ್ಟ್ರೀಯ ಸೈಬರ್ ಪೋರ್ಟಲ್ ವಂಚಕರ ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ತಕ್ಷಣವೇ ಸ್ಥಗಿತಗೊಳಿಸಬಹುದು.",
      "callBtn": "1930 ಗೆ ಕರೆ ಮಾಡಿ",
      "portalBtn": "ಅಧಿಕೃತ ಪೋರ್ಟಲ್ (MHA)",
      "dossierBtn": "ಎಫ್‌ಐಆರ್ ದಾಖಲೆ ಸಿದ್ಧಪಡಿಸಿ"
    },
    "verifyWorkspace": {
      "breadcrumbHome": "ಮುಖಪುಟ",
      "breadcrumbWorkspace": "ನಾಗರಿಕ ಪರಿಶೀಲನಾ ವರ್ಕ್‌ಸ್ಪೇಸ್",
      "engineVersion": "ಎಐ ಶೀಲ್ಡ್ ಎಂಜಿನ್ v4.2",
      "registryConnected": "ಸೆಬಿ ಮತ್ತು ಎನ್‌ಪಿಸಿಐ ನೋಂದಣಿ: ಸಂಪರ್ಕಗೊಂಡಿದೆ",
      "ramProcessed": "100% ರ್‍ಯಾಮ್ ಸುರಕ್ಷಿತ ಪ್ರಕ್ರಿಯೆ",
      "title": "ಹಣ ಪಾವತಿಸುವ ಮುನ್ನ ಪರಿಶೀಲಿಸಿ",
      "subtitle": "ಯಾವುದೇ ಹೂಡಿಕೆ ಸಲಹೆ, ಟೆಲಿಗ್ರಾಂ ಟಿಪ್ ಅಥವಾ ಯುಪಿಐ ಪಾವತಿ ವಿನಂತಿಯನ್ನು ಕೂಲಂಕಷವಾಗಿ ಪರಿಶೀಲಿಸಿ.",
      "tabScreenshot": "ಸ್ಕ್ರೀನ್‌ಶಾಟ್",
      "tabLink": "ಲಿಂಕ್ / ಡೊಮೇನ್",
      "tabMessage": "ಸಂದೇಶ",
      "tabVoice": "ಧ್ವನಿ / ಆಡಿಯೋ",
      "dropzoneTitle": "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅನ್ನು ಇಲ್ಲಿ ಡ್ರ್ಯಾಗ್ ಮಾಡಿ ಹಾಕಿ, ಅಥವಾ",
      "browseFiles": "ಫೈಲ್‌ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
      "dropzoneHint": "(ಜೆಪಿಜಿ, ಪಿಎನ್‌ಜಿ, ವಾಟ್ಸಾಪ್ ಚಾಟ್, ಟೆಲಿಗ್ರಾಂ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ 10 ಎಂಬಿ ವರೆಗೆ)",
      "ocrTag": "ಒಸಿಆರ್ ಪಠ್ಯ ಹೊರತೆಗೆಯುವಿಕೆ",
      "qrTag": "ಯುಪಿಐ ಕ್ಯೂಆರ್ ಕೋಡ್ ಪಾರ್ಸಿಂಗ್",
      "sealTag": "ನಕಲಿ ಮುದ್ರೆ ಪತ್ತೆ",
      "sampleHeading": "ಅಥವಾ ಪೂರ್ವಭಾವಿಯಾಗಿ ಲೋಡ್ ಮಾಡಲಾದ ಭಾರತೀಯ ವಂಚನೆ ಮಾದರಿಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ:",
      "clickToTest": "ಪರೀಕ್ಷಿಸಲು ಯಾವುದನ್ನಾದರೂ ಕ್ಲಿಕ್ ಮಾಡಿ",
      "linkLabel": "ಪರಿಶೀಲಿಸಲು ವೆಬ್‌ಸೈಟ್ ಲಿಂಕ್ ಅಥವಾ ಡೊಮೇನ್ ನಮೂದಿಸಿ:",
      "linkPlaceholder": "ಉದಾ: https://fake-investment-fund.in ಅಥವಾ telegram.me/vip_calls",
      "inspectUrlBtn": "ಡೊಮೇನ್ ಮತ್ತು ಎಸ್‌ಎಸ್‌ಎಲ್ ಪರಿಶೀಲಿಸಿ",
      "messageLabel": "ಅನುಮಾನಾಸ್ಪದ ಸಂದೇಶ ಅಥವಾ ವಾಟ್ಸಾಪ್ ಪಠ್ಯವನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ:",
      "messagePlaceholder": "ವಿದ್ಯುತ್ ಬಿಲ್ ಕಡಿತದ ಎಚ್ಚರಿಕೆ, ಲಾಟರಿ ಗೆಲುವಿನ ಸಂದೇಶ, ಮನೆಯಿಂದಲೇ ಕೆಲಸದ ಆಫರ್...",
      "inspectMsgBtn": "ಎಐ ಪಠ್ಯ ವಿಶ್ಲೇಷಣೆ ನಡೆಸಿ",
      "voiceTitle": "ಕರೆ ರೆಕಾರ್ಡಿಂಗ್ ಅಥವಾ ಆಡಿಯೋ ಕ್ಲಿಪ್ ಅಪ್‌ಲೋಡ್ / ರೆಕಾರ್ಡ್ ಮಾಡಿ",
      "voiceDesc": "ಡೀಪ್‌ಫೇಕ್ ಧ್ವನಿ ಮತ್ತು ಬೆದರಿಕೆ ಕರೆಗಳ ಸ್ಪೆಕ್ಟ್ರಮ್ ವಿಶ್ಲೇಷಣೆ.",
      "startRecord": "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
      "stopRecord": "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
      "uploadAudio": "ಆಡಿಯೋ ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
      "analyzing": "ಎಐ ವಿಧಿವಿಜ್ಞಾನ ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ...",
      "analyzingSub": "ಸೆಬಿ, ಎನ್‌ಪಿಸಿಐ ಮತ್ತು ಸೈಬರ್ ಅಪರಾಧ ದತ್ತಸಂಚಯ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
      "fullAuditBtn": "ಸಂಪೂರ್ಣ ವಿಧಿವಿಜ್ಞಾನ ವರದಿ ರಚಿಸಿ"
    },
    "footer": {
      "advisoryTitle": "ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆ:",
      "advisoryText": "ಸಂಜ್ಞಾನ್ ಶೀಲ್ಡ್ ಹೂಡಿಕೆ ಸಲಹೆ ನೀಡುವುದಿಲ್ಲ. ಹಣ ವರ್ಗಾಯಿಸುವ ಮುನ್ನ ಗುರುತು, ಪರವಾನಗಿ ಮತ್ತು ವಂಚನೆ ಮಾದರಿಗಳನ್ನು ಮಾತ್ರ ನಾವು ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸುತ್ತೇವೆ.",
      "brandDesc": "ಭಾರತಕ್ಕಾಗಿ ರಾಷ್ಟ್ರೀಯ ನಾಗರಿಕ ಫಿನ್‌ಟೆಕ್ ಎಐ ಪರಿಶೀಲನಾ ರಕ್ಷಣಾ ಕವಚ. ಯುಪಿಐ ವಂಚನೆಗಳು ಮತ್ತು ನಕಲಿ ಅಪ್ಲಿಕೇಶನ್‌ಗಳಿಂದ ರಕ್ಷಣೆ.",
      "confidentialBadge": "100% ಗೌಪ್ಯತೆ • ಭಾರತಕ್ಕಾಗಿ ನಿರ್ಮಿತ • ಶೂನ್ಯ ಡೇಟಾ ಮಾರಾಟ",
      "portalsHeading": "ಸಂಸ್ಥಾಗತ ಪೋರ್ಟಲ್‌ಗಳು",
      "navHeading": "ತ್ವರಿತ ನ್ಯಾವಿಗೇಷನ್",
      "helplineHeading": "ತುರ್ತು ನೆರವು",
      "rights": "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ. ನಾಗರಿಕ ಸೈಬರ್ ಭದ್ರತಾ ಉಪಕ್ರಮ."
    }
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('sangyan_lang') || 'hi'
  })

  const setLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode)
      localStorage.setItem('sangyan_lang', langCode)
    }
  }

  const t = TRANSLATIONS[currentLang] || TRANSLATIONS.en

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
